Repository NREL/OpenStudio, pull requests merged in 2019-10, with the labels that each got.

#3711 Add methods to AvailablityManagerNightCycle (applicabilitySchedule) and hide attributes in OS App
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAvailabilityManagerNightCycle.cpp
  openstudiocore/src/energyplus/Test/AvailabilityManagerNightCycle_GTest.cpp
  openstudiocore/src/model/AvailabilityManagerNightCycle.cpp
  openstudiocore/src/model/AvailabilityManagerNightCycle.hpp
  openstudiocore/src/model/AvailabilityManagerNightCycle_Impl.hpp
  openstudiocore/src/model/FanConstantVolume.cpp
  openstudiocore/src/model/FanVariableVolume.cpp
  openstudiocore/src/model/ScheduleTypeRegistry.cpp
  openstudiocore/src/model/test/AvailabilityManagerNightCycle_GTest.cpp
  openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml
  openstudiocore/src/osversion/VersionTranslator.cpp
  openstudiocore/src/osversion/VersionTranslator.hpp
Labels: Pull Request - Ready for CI

#3716 #3711 followup (minor, just a comment thing)
  openstudiocore/src/model/AvailabilityManagerNightCycle.cpp
Labels: Developer Issue

#3676 Use conan swig_installer 4.0
  CMakeLists.txt
  ConanInstall.cmake
  ProjectMacros.cmake
  src/cli/CMakeLists.txt
  src/utilities/CMakeLists.txt
Labels: Pull Request - Ready for CI

#3732 Add QtGUI_ to all unit tests that use QWidget
  openstudiocore/src/model_editor/test/InspectorDialog_GTest.cpp
  openstudiocore/src/model_editor/test/ModalDialogs_GTest.cpp
  openstudiocore/src/openstudio_lib/test/IconLibrary_GTest.cpp
  openstudiocore/src/utilities/core/test/UpdateManager_GTest.cpp
  openstudiocore/src/utilities/filetypes/test/WorkflowJSON_GTest.cpp
  openstudiocore/src/utilities/plot/Test/ProgressBar_GTest.cpp
  openstudiocore/src/utilities/sql/Test/IlluminanceMap_GTest.cpp
Labels: Pull Request - Ready for CI

#3727 Finish removing "additional_ruby_libs"
  CMakeLists.txt
  src/cli/CMakeLists.txt
Labels: Develop3, Pull Request - Ready for CI

#3715 Add new choices for Shading Control Type in IDD
  openstudiocore/resources/model/OpenStudio.idd
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateShadingControl.cpp
Labels: IDDChange, Pull Request - Ready for CI

#3736 Skip cli openssl check on mac
  openstudiocore/CMakeLists.txt
  openstudiocore/src/cli/test/test_embedded_ruby.rb
  openstudiocore/src/utilities/core/test/PathWatcher_GTest.cpp
Labels: Pull Request - Ready for CI

#3642 Fix #2796 - No rule to make target 'src/utilities/idd/IddFieldEnums.ixx'
  openstudiocore/ProjectMacros.cmake
Labels: Developer Issue, Pull Request - Ready for CI

#3738 Fix #2796 but for develop3
  ProjectMacros.cmake
Labels: Pull Request - Ready for CI

#3739 Merge city
  developer/ruby/.gitignore
  developer/ruby/DeprecatedMethods.rb
  developer/ruby/deprecated_methods.csv
  openstudiocore/CMakeLists.txt
  openstudiocore/OpenStudio.in
  openstudiocore/csharp/CMakeLists.txt
  openstudiocore/embedded/CMakeLists.txt
  openstudiocore/embedded/CreateEmbeddedSource.manifest.xml
  openstudiocore/src/cli/CMakeLists.txt
  openstudiocore/src/energyplus/ForwardTranslator.cpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateInternalMass.cpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSurface.cpp
  openstudiocore/src/model/Building.cpp
  openstudiocore/src/model/Building.hpp
  openstudiocore/src/model/BuildingStory.cpp
  openstudiocore/src/model/BuildingStory.hpp
  openstudiocore/src/model/BuildingStory_Impl.hpp
  openstudiocore/src/model/Building_Impl.hpp
  openstudiocore/src/model/ScheduleRule.cpp
  openstudiocore/src/model/ScheduleRule.hpp
  openstudiocore/src/model/ScheduleRule_Impl.hpp
  openstudiocore/src/model/ScheduleTypeRegistry.cpp
  openstudiocore/src/model/ScheduleTypeRegistry.hpp
  openstudiocore/src/model/test/BuildingStory_GTest.cpp
  openstudiocore/src/model/test/Building_GTest.cpp
  openstudiocore/src/model/test/ScheduleRule_GTest.cpp
  openstudiocore/src/openstudio_app/CMakeLists.txt
Labels: Pull Request - Ready for CI

#3747 Fix bug related to json
  src/cli/main.cpp
Labels: Pull Request - Ready for CI

#3749 Further improve ZonePropertyUserViewFactorsBySurfaceName performance
  openstudiocore/src/model/ZonePropertyUserViewFactorsBySurfaceName.cpp
  openstudiocore/src/utilities/idf/WorkspaceExtensibleGroup.cpp
  openstudiocore/src/utilities/idf/WorkspaceExtensibleGroup.hpp
  openstudiocore/src/utilities/idf/WorkspaceObject.cpp
  openstudiocore/src/utilities/idf/WorkspaceObject.hpp
  openstudiocore/src/utilities/idf/WorkspaceObject_Impl.hpp
Labels: Pull Request - Ready for CI

#3751 removing json/ext check as this is statically linked in cli
  src/cli/embedded_help.rb
Labels: Pull Request - Ready for CI
