Repository NREL/OpenStudio, pull requests merged in 2019-09, with the labels that each got.

#3565 Add More Coil and Tank Choices for Desuperheater
  openstudiocore/resources/model/OpenStudio.idd
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilWaterHeatingDesuperheater.cpp
  openstudiocore/src/energyplus/Test/CoilWaterHeatingDesuperheater_GTest.cpp
  openstudiocore/src/model/CoilWaterHeatingDesuperheater.cpp
  openstudiocore/src/model/CoilWaterHeatingDesuperheater.hpp
  openstudiocore/src/model/CoilWaterHeatingDesuperheater_Impl.hpp
  openstudiocore/src/model/test/CoilWaterHeatingDesuperheater_GTest.cpp
Labels: Pull Request - Ready for CI

#3663 #3584 add Temperature Difference Between Cutout And Setpoint for ZoneControl:Thermostat
  openstudiocore/resources/energyplus/ProposedEnergy+.idd
  openstudiocore/resources/model/OpenStudio.idd
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermostatSetpointDualSetpoint.cpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneControlThermostatStagedDualSetpoint.cpp
  openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateZone.cpp
  openstudiocore/src/energyplus/Test/ThermostatSetpointDualSetpoint_GTest.cpp
  openstudiocore/src/model/ThermostatSetpointDualSetpoint.cpp
  openstudiocore/src/model/ThermostatSetpointDualSetpoint.hpp
  openstudiocore/src/model/ThermostatSetpointDualSetpoint_Impl.hpp
Labels: Pull Request - Ready for CI

#3661 #3649 pump variable speed E+ change
  openstudiocore/resources/model/OpenStudio.idd
  openstudiocore/src/model/PumpVariableSpeed.cpp
  openstudiocore/src/utilities/units/IddUnitString.cpp
Labels: Pull Request - Ready for CI

#3659 Fix #3654: Add ThermalStorage:Ice:Detailed "(Dis)charging Curve Variable Specifications"
  openstudiocore/resources/model/OpenStudio.idd
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalStorageIceDetailed.cpp
  openstudiocore/src/model/ThermalStorageIceDetailed.cpp
  openstudiocore/src/model/ThermalStorageIceDetailed.hpp
  openstudiocore/src/model/ThermalStorageIceDetailed_Impl.hpp
  openstudiocore/src/osversion/VersionTranslator.cpp
  openstudiocore/src/osversion/VersionTranslator.hpp
Labels: IDDChange, Pull Request - Ready for CI

#3602 Fix #3600: display plantLoop supply equipment in the same order as the resulting PlantEquipmentList after ForwardTranslaton
  openstudiocore/src/openstudio_lib/GridItem.cpp
Labels: Pull Request - Ready for CI

#3634 Display non-zero north angle
  openstudiocore/src/openstudio_lib/library/geometry_preview.html
Labels: Pull Request - Ready for CI, component - OS App

#3667 Some post-merges fixes
  openstudiocore/resources/energyplus/ProposedEnergy+.idd
  openstudiocore/resources/model/OpenStudio.idd
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalStorageIceDetailed.cpp
  openstudiocore/src/model/AirLoopHVACUnitarySystem.cpp
Labels: IDDChange, Pull Request - Ready for CI

#3672 Add new Fields in AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass
  openstudiocore/resources/model/OpenStudio.idd
  openstudiocore/src/energyplus/CMakeLists.txt
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.cpp
  openstudiocore/src/energyplus/Test/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass_GTest.cpp
  openstudiocore/src/model/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.cpp
  openstudiocore/src/model/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.hpp
  openstudiocore/src/model/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass_Impl.hpp
  openstudiocore/src/model/test/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass_GTest.cpp
  openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml
  openstudiocore/src/osversion/VersionTranslator.cpp
Labels: IDDChange, Pull Request - Ready for CI, component - HVAC

#3675 Wrap ZoneProperty:UserViewFactors:bySurfaceName object
  openstudiocore/resources/model/OpenStudio.idd
  openstudiocore/src/energyplus/CMakeLists.txt
  openstudiocore/src/energyplus/ForwardTranslator.cpp
  openstudiocore/src/energyplus/ForwardTranslator.hpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSurfacePropertyConvectionCoefficients.cpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZonePropertyUserViewFactorsBySurfaceName.cpp
  openstudiocore/src/energyplus/ReverseTranslator.cpp
  openstudiocore/src/energyplus/ReverseTranslator.hpp
  openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateZonePropertyUserViewFactorsBySurfaceName.cpp
  openstudiocore/src/energyplus/Test/ReverseTranslator_GTest.cpp
  openstudiocore/src/energyplus/Test/ZonePropertyUserViewFactorsBySurfaceName_GTest.cpp
  openstudiocore/src/model/CMakeLists.txt
  openstudiocore/src/model/ConcreteModelObjects.hpp
  openstudiocore/src/model/Model.cpp
  openstudiocore/src/model/ModelGeometry.i
  openstudiocore/src/model/ThermalZone.cpp
  openstudiocore/src/model/ThermalZone.hpp
  openstudiocore/src/model/ThermalZone_Impl.hpp
  openstudiocore/src/model/ZonePropertyUserViewFactorsBySurfaceName.cpp
  openstudiocore/src/model/ZonePropertyUserViewFactorsBySurfaceName.hpp
  openstudiocore/src/model/ZonePropertyUserViewFactorsBySurfaceName_Impl.hpp
  openstudiocore/src/model/test/ZonePropertyUserViewFactorsBySurfaceName_GTest.cpp
Labels: IDDChange, Pull Request - Ready for CI, component - Model

#3673 Update embeddable_gbxml_editor.html to match new build from @theo-arm…
  openstudiocore/src/openstudio_lib/library/embeddable_gbxml_editor.html
Labels: Pull Request - Ready for CI, component - OS App, component - gbXML

#3677 V2.9.0 rc1
  openstudiocore/CMakeLists.txt
  openstudiocore/pat/CMakeLists.txt
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateTableMultiVariableLookup.cpp
  openstudiocore/src/model/CoilCoolingDXSingleSpeed.cpp
  openstudiocore/src/model/CoilCoolingDXTwoSpeed.cpp
  openstudiocore/src/model/ExternalFile.cpp
  openstudiocore/src/utilities/sql/Test/SqlFileFixture.cpp
  openstudiocore/src/utilities/sql/Test/SqlFileFixture.hpp
  openstudiocore/src/utilities/sql/Test/SqlFile_GTest.cpp
Labels: Pull Request - Ready for CI

#3692 Add missing methods for HeaderedPumpsConstantSpeed and HeaderedPumpsVariableSpeed
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateHeaderedPumpsConstantSpeed.cpp
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateHeaderedPumpsVariableSpeed.cpp
  openstudiocore/src/model/HeaderedPumpsConstantSpeed.cpp
  openstudiocore/src/model/HeaderedPumpsConstantSpeed.hpp
  openstudiocore/src/model/HeaderedPumpsConstantSpeed_Impl.hpp
  openstudiocore/src/model/HeaderedPumpsVariableSpeed.cpp
  openstudiocore/src/model/HeaderedPumpsVariableSpeed.hpp
  openstudiocore/src/model/HeaderedPumpsVariableSpeed_Impl.hpp
  openstudiocore/src/model/test/HeaderedPumpsConstantSpeed_GTest.cpp
  openstudiocore/src/model/test/HeaderedPumpsVariableSpeed_GTest.cpp
  openstudiocore/src/osversion/VersionTranslator.cpp
Labels: Pull Request - Ready for CI
