Repository NREL/OpenStudio, pull requests merged in 2019-12, with the labels that each got.

#3787 Add methods to ForwardTranslator to exclude standard output requests
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
Labels: Develop3, Pull Request - Ready for CI, component - IDF Translation

#3804 Removes ShadingControl warning
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateShadingControl.cpp
Labels: Pull Request - Ready for CI, component - IDF Translation

#3781 Fix bug of ITE object supply/approach temperature difference schedule
  openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipmentITEAirCooled.cpp
  openstudiocore/src/energyplus/Test/ElectricEquipmentITEAirCooled_GTest.cpp
  openstudiocore/src/model/ScheduleTypeRegistry.cpp
  openstudiocore/src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp
Labels: Pull Request - Ready for CI, component - Model

#3808 Move PathWatcher/WorkspaceWatcher ruby tests to OpenStudioApplication
  ruby/test/PathWatcher_Test.rb
  ruby/test/WorkspaceWatcher_Test.rb
Labels: Develop3

#3818 Merge develops
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_develop_format
  OpenStudio.in
  ci/clang-format.sh
  csharp/CMakeLists.txt
  developer/ruby/.gitignore
  developer/ruby/DeprecatedMethods.rb
  developer/ruby/deprecated_methods.csv
  embedded/CMakeLists.txt
  embedded/CreateEmbeddedSource.manifest.xml
  pat/CMakeLists.txt
  resources/energyplus/ProposedEnergy+.idd
  src/.clang-format
  src/cli/CMakeLists.txt
  src/cli/test/test_embedded_ruby.rb
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipmentITEAirCooled.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateInternalMass.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateShadingControl.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSurface.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateTableMultiVariableLookup.cpp
  src/energyplus/Test/ElectricEquipmentITEAirCooled_GTest.cpp
  src/energyplus/Test/PlantEquipmentOperationSchemes_GTest.cpp
  src/energyplus/Test/TableMultiVariableLookup_GTest.cpp
  src/model/Building.cpp
  src/model/Building.hpp
  src/model/BuildingStory.cpp
  src/model/BuildingStory.hpp
  src/model/BuildingStory_Impl.hpp
  src/model/Building_Impl.hpp
  src/model/ModelExtensibleGroup.cpp
  src/model/ModelExtensibleGroup.hpp
  src/model/ModelObject.cpp
  src/model/ScheduleRule.cpp
  src/model/ScheduleRule.hpp
  src/model/ScheduleRule_Impl.hpp
  src/model/ScheduleTypeRegistry.cpp
  src/model/ScheduleTypeRegistry.hpp
  src/model/ThermalZone.cpp
  src/model/ThermalZone.hpp
  src/model/ThermalZone_Impl.hpp
  src/model/ZoneHVACEquipmentList.cpp
  src/model/ZoneHVACEquipmentList.hpp
  src/model/ZoneHVACEquipmentList_Impl.hpp
  src/model/ZonePropertyUserViewFactorsBySurfaceName.cpp
  src/model/test/BuildingStory_GTest.cpp
  src/model/test/Building_GTest.cpp
  src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp
  src/model/test/ScheduleRule_GTest.cpp
  src/model/test/ZoneHVACEquipmentList_GTest.cpp
  src/utilities/core/test/UpdateManager_GTest.cpp
  src/utilities/filetypes/test/WorkflowJSON_GTest.cpp
  src/utilities/idf/WorkspaceExtensibleGroup.cpp
  src/utilities/idf/WorkspaceExtensibleGroup.hpp
  src/utilities/idf/WorkspaceObject.cpp
  src/utilities/idf/WorkspaceObject.hpp
  src/utilities/idf/WorkspaceObject_Impl.hpp
  src/utilities/sql/Test/IlluminanceMap_GTest.cpp
Labels: Pull Request - Ready for CI

#2800 Pitched roofs
  openstudiocore/src/utilities/CMakeLists.txt
  openstudiocore/src/utilities/geometry/Geometry.cpp
  openstudiocore/src/utilities/geometry/Geometry.hpp
  openstudiocore/src/utilities/geometry/Point3d.cpp
  openstudiocore/src/utilities/geometry/Point3d.hpp
  openstudiocore/src/utilities/geometry/RoofGeometry.cpp
  openstudiocore/src/utilities/geometry/RoofGeometry.hpp
  openstudiocore/src/utilities/geometry/Test/RoofGeometry_GTest.cpp
  openstudiocore/src/utilities/geometry/Vector3d.cpp
  openstudiocore/src/utilities/geometry/Vector3d.hpp
Labels: Pull Request - Ready for CI

#3821 Temporarily adjsut conan dependencies to be able to build develop
  ConanInstall.cmake
  Jenkinsfile_develop3
  Jenkinsfile_develop_format
  src/utilities/geometry/RoofGeometry.cpp
Labels: Developer Issue, Pull Request - Ready for CI, severity - Blocker

#3824 Update conan deps
  .gitignore
  CMakeLists.txt
  ConanInstall.cmake
  ProjectMacros.cmake
  embedded/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/generateiddfactory/CMakeLists.txt
  src/install_utility/CMakeLists.txt
  src/utilities/CMakeLists.txt
Labels: Developer Issue, Pull Request - Ready for CI

#3829 cpprestsdk bincrafters/stable now includes the changes we need
  ConanInstall.cmake
Labels: Developer Issue, Pull Request - Ready for CI
