Repository NREL/OpenStudio, pull requests merged in 2020-11, with the labels that each got.

#4136 Fix #4125, Fix #4135 - GbXML ForwardTranslator: clear map&set, and add a modelToGbXMLString method
  src/gbxml/ForwardTranslator.cpp
  src/gbxml/ForwardTranslator.hpp
  src/gbxml/Test/ForwardTranslator_GTest.cpp
Labels: Pull Request - Ready for CI, component - gbXML

#4122 Fix #3964 - Adjustments to python bindings and produce a pypi package
  CMakeLists.txt
  ProjectMacros.cmake
  python/CMakeLists.txt
  python/FixPythonImports.cmake
  python/openstudio.py
  python/openstudio_dynamic.py
  python/setup.py
  python/testpath.py
  src/model/Model.i
  src/model/ModelAirflow.i
  src/model/ModelAvailabilityManager.i
  src/model/ModelCore.i
  src/model/ModelGenerators.i
  src/model/ModelGeometry.i
  src/model/ModelHVAC.i
  src/model/ModelPlantEquipmentOperationScheme.i
  src/model/ModelRefrigeration.i
  src/model/ModelResources.i
  src/model/ModelSimulation.i
  src/model/ModelStraightComponent.i
  src/model/ModelZoneHVAC.i
  src/model/Model_Common_Include.i
  src/model/ResourceObject.cpp
  src/utilities/bcl/LocalBCL.cpp
  src/utilities/geometry/Intersection.cpp
  src/utilities/units/Unit.i
Labels: Pull Request - Ready for CI, component - Installer/Platform

#4124 Fix #4102 - Add missing VersionTranslation for EMS Actuator fuel type rename
  src/osversion/VersionTranslator.cpp
Labels: Pull Request - Ready for CI

#4128 V3.1.0 fixed sqlite3 linkage
  src/lib/CMakeLists.txt
  src/utilities/UtilitiesSql.i
  src/utilities/sql/CMakeLists.txt
  src/utilities/sql/PreparedStatement.cpp
  src/utilities/sql/PreparedStatement.hpp
  src/utilities/sql/SqlFile_Impl.hpp
Labels: Pull Request - Ready for CI, component - Utilities Other, severity - Normal Bug

#4130 In SqlFile trap case when EnergyPlus year is 0
  src/utilities/sql/SqlFile_Impl.cpp
Labels: Pull Request - Ready for CI, severity - Major Bug

#4069 637 speedup version translation new parsing method
  src/utilities/core/ASCIIStrings.hpp
  src/utilities/core/test/String_GTest.cpp
  src/utilities/idd/IddField.cpp
  src/utilities/idd/IddFile.cpp
  src/utilities/idd/IddObject.cpp
Labels: Enhancement Request, Pull Request - Ready for CI, component - Version Translator

#4137 Addresses #4076, radiant system enhancements
  resources/model/OpenStudio.idd
Labels: Pull Request - Ready for CI, component - Model

#4143 Add a cppcheck.yml workflow file
  .github/workflows/cppcheck.yml
Labels: Developer Issue

#4145 Issue_4043
  src/utilities/bcl/test/BCL_GTest.cpp
  src/utilities/sql/Test/SqlFile_GTest.cpp
Labels: Pull Request - Ready for CI, component - Utilities Other, severity - Minor Bug
