Repository NREL/OpenStudio, pull requests merged in 2020-08, with the labels that each got.

#4002 remove if defaulted statements
  src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
Labels: Pull Request - Ready for CI

#4023 Addresses #3936, subSurface Type reset when assigned to surface
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp
  src/model/SubSurface.cpp
  src/model/SubSurface.hpp
  src/model/SubSurface_Impl.hpp
Labels: Pull Request - Ready for CI, component - Model, severity - Minor Bug

#4028 3835 improve cli runtime
  embedded/embedded_files.cxx.in
  embedded/embedded_files.hxx.in
  ruby/init_openstudio.cpp
  ruby/init_openstudio.hpp
  src/cli/CMakeLists.txt
  src/cli/embedded_help.rb
  src/cli/main.cpp
  src/cli/openstudio_cli.rb
  src/cli/openstudio_init_extended.rb
Labels: Enhancement Request, Pull Request - Ready for CI

#3989 Fix #3076 - make openstudio::Vector "Enumerable" in ruby
  src/utilities/data/Vector.i
Labels: Pull Request - Ready for CI, component - Utilities Other

#4024 Addresses #3578, warning message when running measure test 'Cannot find current Workflow Step'
  src/measure/OSRunner.cpp
Labels: Pull Request - Ready for CI, component - WorkflowJSON, severity - Normal Bug

#4030 Fix #4020 - AvailabilityManagerNightCycle: Ensure ModelObjectLists are handled in clone/remove
  src/model/AvailabilityManagerNightCycle.cpp
  src/model/AvailabilityManagerNightCycle_Impl.hpp
  src/model/test/AvailabilityManagerNightCycle_GTest.cpp
Labels: Pull Request - Ready for CI

#4032 Fix #4016 - Move VT from 2.9.0 to 3.0.0 for new fields at end of the ZoneHVAC:TerminalUnit:VariableRefrigerantFlow
  src/osversion/VersionTranslator.cpp
Labels: Pull Request - Ready for CI, component - HVAC, component - Version Translator, severity - Normal Bug

#3996 Fix #3990 - Add an API to CoilCoolingDXMultiSpeed to add/remove stages
  resources/model/OpenStudio.idd
  src/model/CoilCoolingDXMultiSpeed.cpp
  src/model/CoilCoolingDXMultiSpeed.hpp
  src/model/CoilCoolingDXMultiSpeedStageData.cpp
  src/model/CoilCoolingDXMultiSpeedStageData.hpp
  src/model/CoilCoolingDXMultiSpeedStageData_Impl.hpp
  src/model/CoilCoolingDXMultiSpeed_Impl.hpp
  src/model/FanSystemModel.cpp
  src/model/ModelHVAC.i
  src/model/ModelStraightComponent.i
  src/model/test/CoilCoolingDXMultiSpeedStageData_GTest.cpp
  src/model/test/CoilCoolingDXMultiSpeed_GTest.cpp
Labels: IDDChange, Pull Request - Ready for CI, component - HVAC, severity - Minor Bug

#4040 Fix #4038 - Re-enable `-Wall` on Unix
  CMakeLists.txt
  ProjectMacros.cmake
  src/cli/RubyInterpreter.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateTableMultiVariableLookup.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateFanSystemModel.cpp
  src/model/FanSystemModel.cpp
  src/model/OutputTableSummaryReports.cpp
  src/model/ShadowCalculation.cpp
  src/osversion/VersionTranslator.cpp
  src/sdd/MapHVAC.cpp
  src/utilities/data/Attribute.cpp
  src/utilities/geometry/RoofGeometry_Details.hpp
  src/utilities/sql/Test/SqlFile_GTest.cpp
  src/utilities/units/test/OSQuantityVector_GTest.cpp
Labels: Developer Issue, Pull Request - Ready for CI

#4029 Solution for silent install on windows?
  install.qs
Labels: Pull Request - Ready for CI

#4011 Fix #1675 - ForwardTranslate WaterHeater:Mixed when not on loop but has Peak Use Flow Rate (standalone operation)
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateWaterHeaterMixed.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateWaterHeaterStratified.cpp
  src/energyplus/Test/GeneratorMicroTurbine_GTest.cpp
  src/energyplus/Test/WaterHeaterMixed_GTest.cpp
  src/energyplus/Test/WaterHeaterStratified_GTest.cpp
  src/model/GeneratorMicroTurbine.cpp
  src/model/GeneratorMicroTurbine_Impl.hpp
Labels: Pull Request - Ready for CI, component - HVAC, component - IDF Translation

#4045 Bump conan min version to 1.28 or sqlite3 recipe will throw an error
  ConanInstall.cmake
Labels: Developer Issue, Pull Request - Ready for CI

#4015 Conan bump deps
  CMakeLists.txt
  ConanInstall.cmake
Labels: Developer Issue, Pull Request - Ready for CI

#4047 Pin the actual recipe revisions for all conan dependencies
  ConanInstall.cmake
Labels: Developer Issue, Pull Request - Ready for CI

#4049 Test actual MSVC patch for conan openstudio ruby
  ConanInstall.cmake
Labels: Developer Issue, Pull Request - Ready for CI

#4055 Add Site, Facility, and Building to ModelMerger
  resources/utilities/Geometry/floorplan.json
  src/model/BuildingStory.cpp
  src/model/BuildingStory.hpp
  src/model/BuildingStory_Impl.hpp
  src/model/ModelMerger.cpp
  src/model/ModelMerger.hpp
  src/model/PlanarSurfaceGroup.cpp
  src/model/PlanarSurfaceGroup.hpp
  src/model/PlanarSurfaceGroup_Impl.hpp
  src/model/ThreeJSForwardTranslator.cpp
  src/model/ThreeJSReverseTranslator.cpp
  src/model/ThreeJSReverseTranslator.hpp
  src/model/test/FloorplanJSForwardTranslator_GTest.cpp
  src/model/test/ModelMerger_GTest.cpp
  src/utilities/geometry/FloorplanJS.cpp
  src/utilities/geometry/FloorplanJS.hpp
  src/utilities/geometry/Test/FloorplanJS_GTest.cpp
Labels: Pull Request - Ready for CI, component - Geometry Editor

#4059 OutputControl:Files
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateOutputControlFiles.cpp
  src/energyplus/ReverseTranslator.cpp
  src/energyplus/ReverseTranslator.hpp
  src/energyplus/ReverseTranslator/ReverseTranslateOutputControlFiles.cpp
  src/energyplus/Test/OutputControlFiles_GTest.cpp
  src/model/CMakeLists.txt
  src/model/ConcreteModelObjects.hpp
  src/model/Model.cpp
  src/model/Model.hpp
  src/model/ModelSimulation.i
  src/model/Model_Impl.hpp
  src/model/OutputControlFiles.cpp
  src/model/OutputControlFiles.hpp
  src/model/OutputControlFiles_Impl.hpp
  src/model/test/OutputControlFiles_GTest.cpp
  src/model/test/UniqueModelObject_GTest.cpp
Labels: Enhancement Request, IDDChange, Pull Request - Ready for CI, component - Model
