Repository NREL/OpenStudio, pull requests merged in 2020-05, with the labels that each got.

#3920 RefrigerationSystem fixes
  src/model/RefrigerationAirChiller.cpp
  src/model/RefrigerationAirChiller.hpp
  src/model/RefrigerationAirChiller_Impl.hpp
  src/model/RefrigerationCase.cpp
  src/model/RefrigerationCase.hpp
  src/model/RefrigerationCase_Impl.hpp
  src/model/RefrigerationCompressor.cpp
  src/model/RefrigerationCompressor.hpp
  src/model/RefrigerationCompressor_Impl.hpp
  src/model/RefrigerationCondenserCascade.cpp
  src/model/RefrigerationCondenserCascade.hpp
  src/model/RefrigerationCondenserCascade_Impl.hpp
  src/model/RefrigerationSecondarySystem.cpp
  src/model/RefrigerationSecondarySystem.hpp
  src/model/RefrigerationSecondarySystem_Impl.hpp
  src/model/RefrigerationSystem.cpp
  src/model/RefrigerationWalkIn.cpp
  src/model/RefrigerationWalkIn.hpp
  src/model/RefrigerationWalkIn_Impl.hpp
  src/model/test/RefrigerationSystem_GTest.cpp
Labels: Pull Request - Ready for CI, component - Model

#3923 Fix #871: disable fast naming for the model in RT
  src/energyplus/ReverseTranslator.cpp
Labels: Pull Request - Ready for CI, component - IDF Translation

#3956 Fix #3311 - Bundle tests take too much space
  .git-blame-ignore-revs
  src/cli/test/bundle/Gemfile
  src/cli/test/bundle/test.rb
  src/cli/test/bundle_default/test.rb
  src/cli/test/bundle_native/test.rb
  src/cli/test/bundle_no_install/test.rb
  src/cli/test/no_bundle/test.rb
  src/cli/test/test_bundle.rb
  src/cli/test/test_embedded_help.rb
Labels: Developer Issue, Pull Request - Ready for CI

#3973 #3972 - ScheduleRuleset remove winterDD/summerDD/holiday ScheduleDay in reset
  src/model/ScheduleRuleset.cpp
  src/model/test/ScheduleRuleset_GTest.cpp
Labels: Pull Request - Ready for CI, component - Model, severity - Minor Bug

#3963 Fix #3961 - Fix build error with Python bindings due to zlib's crypt.h
  CMakeLists.txt
  ConanInstall.cmake
  ProjectMacros.cmake
  python/CMakeLists.txt
  python/README.txt
  python/openstudio.py
  python/openstudio_dynamic.py
  python/testpath.py
Labels: Pull Request - Ready for CI

#3971 Fix #3943 - ThreeJS handle ConstructionAirBoundary as "AirWall" material
  CMakeLists.txt
  src/model/ThreeJSForwardTranslator.cpp
  src/model/test/ThreeJSForwardTranslator_GTest.cpp
  src/utilities/geometry/ThreeJS.cpp
Labels: Pull Request - Ready for CI, component - Geometry Editor, severity - Minor Bug

#3970 Bump to conan fmt/6.2.0, and use the recipe option to define FMT_HEADER_ONLY
  ConanInstall.cmake
  src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateScheduleVariableInterval.cpp
  src/utilities/filetypes/EpwFile.cpp
Labels: Developer Issue, Pull Request - Ready for CI

#3983 Fix #1058 - remove warning when loading DDY file
  src/utilities/idf/IdfFile.cpp
Labels: Pull Request - Ready for CI, component - Utilities Other

#3979 update to new gems
  CMakeLists.txt
Labels: Pull Request - Ready for CI
