Repository NREL/OpenStudio, pull requests merged in 2020-01, with the labels that each got.

#3833 Update min version to conan 1.21.0 (to avoid issue with bzip / conan center index)
  ConanInstall.cmake
Labels: Developer Issue, Pull Request - Ready for CI

#3836 Change CONAN_PKG::xxx casing following upstream breaking changes.
  ProjectMacros.cmake
  embedded/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/generateiddfactory/CMakeLists.txt
  src/install_utility/CMakeLists.txt
  src/utilities/CMakeLists.txt
Labels: Developer Issue, Pull Request - Ready for CI

#3834 Native extensions
  CMakeLists.txt
  src/cli/CMakeLists.txt
  src/cli/EmbeddedHelp.hpp
  src/cli/embedded_help.rb
  src/cli/main.cpp
  src/cli/openstudio_cli.rb
Labels: Pull Request - Ready for CI

#3813 Addresses #934, hitting E+ error on specific heat of new default materials
  resources/model/OpenStudio.idd
  src/energyplus/Test/ForwardTranslator_GTest.cpp
  src/energyplus/Test/ReverseTranslator_GTest.cpp
  src/model/StandardOpaqueMaterial.hpp
  src/osversion/VersionTranslator.cpp
  src/osversion/VersionTranslator.hpp
Labels: IDDChange, Pull Request - Ready for CI, component - Model, severity - Major Bug

#3812 Addresses #243, default profile being used when it should not be
  Jenkinsfile_clang_format
  src/energyplus/ForwardTranslator/ForwardTranslateScheduleRuleset.cpp
  src/energyplus/Test/ScheduleRuleset_GTest.cpp
Labels: Pull Request - Ready for CI, component - TimeDate, severity - Blocker

#3849 Add a missing entry in ScheduleTypeRegistry for SurfacePropertyOtherSideCoefficients
  src/model/CMakeLists.txt
  src/model/ScheduleTypeRegistry.cpp
  src/model/SurfacePropertyOtherSideCoefficients.cpp
  src/model/test/SurfacePropertyOtherSideCoefficients_GTest.cpp
Labels: Pull Request - Ready for CI, component - Model

#3845 Make tests order independent
  src/energyplus/Test/AirLoopHVAC_GTest.cpp
  src/energyplus/Test/AirflowNetwork_GTest.cpp
  src/energyplus/Test/CentralHeatPumpSystem_GTest.cpp
  src/energyplus/Test/EMS_GTest.cpp
  src/energyplus/Test/ElectricLoadCenterTransformer_GTest.cpp
  src/energyplus/Test/ErrorFile_GTest.cpp
  src/energyplus/Test/ExternalInterfaceFT_GTest.cpp
  src/energyplus/Test/ForwardTranslator_GTest.cpp
  src/energyplus/Test/FuelCell_GTest.cpp
  src/energyplus/Test/GeneratorMicroTurbine_GTest.cpp
  src/energyplus/Test/PlantComponentUserDefined_GTest.cpp
  src/energyplus/Test/PlantLoop_GTest.cpp
  src/energyplus/Test/ReverseTranslator_GTest.cpp
  src/energyplus/Test/ScheduleInterval_GTest.cpp
  src/model/ZonePropertyUserViewFactorsBySurfaceName.cpp
  src/model/test/CoilWaterHeatingAirToWaterHeatPump_GTest.cpp
  src/model/test/DefaultSurfaceConstructions_GTest.cpp
  src/model/test/ElectricLoadCenterTransformer_GTest.cpp
  src/model/test/EnergyManagementSystemConstructionIndexVariable_GTest.cpp
  src/model/test/EnergyManagementSystemCurveOrTableIndexVariable_GTest.cpp
  src/model/test/EnergyManagementSystemMeteredOutputVariable_GTest.cpp
  src/model/test/EnergyManagementSystemProgramCallingManager_GTest.cpp
  src/model/test/EnergyManagementSystemProgram_GTest.cpp
  src/model/test/EnergyManagementSystemSensor_GTest.cpp
  src/model/test/FloorplanJSForwardTranslator_GTest.cpp
  src/model/test/Model_GTest.cpp
  src/model/test/PlantComponentUserDefined_GTest.cpp
  src/model/test/Space_GTest.cpp
  src/utilities/bcl/BCLXML.cpp
  src/utilities/bcl/LocalBCL.cpp
  src/utilities/bcl/test/BCLFixture.cpp
  src/utilities/bcl/test/BCLFixture.hpp
  src/utilities/bcl/test/BCL_GTest.cpp
  src/utilities/idf/WorkspaceExtensibleGroup.cpp
  src/utilities/idf/WorkspaceObject.cpp
  src/utilities/sql/Test/IlluminanceMap_GTest.cpp
Labels: Developer Issue, Pull Request - Ready for CI, component - Testing

#3855 Fix #3854: autosize ZoneHVACUnitHeater Maximum Water flow rate in Ctor
  src/model/ZoneHVACUnitHeater.cpp
  src/osversion/VersionTranslator.cpp
Labels: Pull Request - Ready for CI, component - HVAC, component - Model

#3860 Versioning adjustments
  CMakeLists.txt
  OpenStudio.in
  OpenStudio.nuspec.in
  ProjectMacros.cmake
  java/CMakeLists.txt
  resources/model/OpenStudio.idd
  src/model/Version.cpp
  src/model/Version.hpp
  src/model/Version_Impl.hpp
  src/utilities/idf/IdfFile.cpp
  v8-node/CMakeLists.txt
Labels: Developer Issue, IDDChange, Pull Request - Ready for CI

#3865 OpenSSL renamed to openssl (lowercase)
  src/utilities/CMakeLists.txt
Labels: Developer Issue

#3842 Allow Installing both OpenStudio (SDK) and OpenStudioApplication via Deb package
  CMakeLists.txt
  debian/postinst.in
  debian/postrm.in
Labels: Pull Request - Ready for CI
