Repository NREL/OpenStudio, pull requests merged in 2020-12, with the labels that each got.

#4149 Addresses #3706, add drain water heat exchanger methods to WaterUseConnections
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator/ForwardTranslateWaterUseConnections.cpp
  src/energyplus/Test/WaterUseConnections_GTest.cpp
  src/model/WaterUseConnections.cpp
  src/model/WaterUseConnections.hpp
  src/model/WaterUseConnections_Impl.hpp
  src/model/test/WaterUseConnections_GTest.cpp
Labels: Enhancement Request, Pull Request - Ready for CI, component - HVAC, component - Model

#4148 Fixes #4147
  src/utilities/bcl/BCLXML.cpp
Labels: Pull Request - Ready for CI, severity - Normal Bug

#4151 fix issue_4132 - hande lower case window drive letters
  src/cli/embedded_help.rb
Labels: Pull Request - Ready for CI, component - CLI, severity - Normal Bug

#4158 Fix #4154 - use the edge cppcheck from snap, since the stable is broken
  .github/workflows/cppcheck.yml
Labels: Developer Issue

#4138 Fix EnergyPlus md5 check for Ubuntu 20.4
  CMakeLists.txt
  src/measure/OSArgument.cpp
  src/model/AdditionalProperties.cpp
  src/utilities/filetypes/EpwFile.cpp
Labels: Pull Request - Ready for CI

#4165 Fix cppcheck !result failures
  src/measure/OSArgument.cpp
  src/model/MaterialPropertyGlazingSpectralData.cpp
  src/model/UnitarySystemPerformanceMultispeed.cpp
  src/utilities/data/Attribute.cpp
Labels: Pull Request - Ready for CI, severity - Normal Bug

#4157 Addresses #2958, add ZoneHVAC:CoolingPanel:RadiantConvective:Water to OpenStudio
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslatePlantLoop.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACCoolingPanelRadiantConvectiveWater.cpp
  src/model/CMakeLists.txt
  src/model/CoilCoolingWaterPanelRadiant.cpp
  src/model/CoilCoolingWaterPanelRadiant.hpp
  src/model/CoilCoolingWaterPanelRadiant_Impl.hpp
  src/model/ConcreteModelObjects.hpp
  src/model/Model.cpp
  src/model/ModelStraightComponent.i
  src/model/ModelZoneHVAC.i
  src/model/ScheduleTypeRegistry.cpp
  src/model/ZoneHVACBaseboardRadiantConvectiveWater.cpp
  src/model/ZoneHVACCoolingPanelRadiantConvectiveWater.cpp
  src/model/ZoneHVACCoolingPanelRadiantConvectiveWater.hpp
  src/model/ZoneHVACCoolingPanelRadiantConvectiveWater_Impl.hpp
  src/model/test/CoilCoolingWaterPanelRadiant_GTest.cpp
  src/model/test/ZoneHVACCoolingPanelRadiantConvectiveWater_GTest.cpp
Labels: Enhancement Request, Pull Request - Ready for CI, component - Model

#4171 Updating openstudio gems.
  CMakeLists.txt
Labels: Enhancement Request, Pull Request - Ready for CI, component - CLI
