Repository NREL/OpenStudio, pull requests merged in 2021-10, with the labels that each got.

#4417 Fix #4156 - Support nested subfolders in approved Measure directories
  src/utilities/bcl/BCLFileReference.cpp
  src/utilities/bcl/BCLFileReference.hpp
  src/utilities/bcl/BCLMeasure.cpp
  src/utilities/bcl/BCLMeasure.hpp
  src/utilities/bcl/BCLXML.cpp
  src/utilities/bcl/test/BCLFileReference_GTest.cpp
  src/utilities/bcl/test/BCLFixture.cpp
  src/utilities/bcl/test/BCLMeasure_GTest.cpp
  src/utilities/core/Filesystem.hpp
  src/utilities/core/Path.cpp
  src/utilities/core/Path.hpp
Labels: Enhancement Request, component - Measure Manager, component - Utilities Other, Pull Request - Ready for CI, APIChange

#4454 Fix #4404 #4453 - Fix issues with ForwardTranslator options
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/Test/ForwardTranslator_GTest.cpp
Labels: severity - Minor Bug, component - IDF Translation, Pull Request - Ready for CI

#4431 Fixed an issue in Surface splitSurfaceForSubSurfaces which caused the…
  src/model/Surface.cpp
  src/model/test/Surface_GTest.cpp
Labels: component - Utilities Geometry, Pull Request - Ready for CI

#4459 Fix #3426 - ZoneHVACUnitHeater components missing air inlet/outlet node names when Fan:OnOff
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACUnitHeater.cpp
  src/energyplus/Test/ZoneHVACUnitHeater_GTest.cpp
Labels: severity - Normal Bug, component - HVAC, component - IDF Translation, Pull Request - Ready for CI

#4466 [Developer] Add Full detailed tests for the FT of SpaceInfiltration objects (whether assigned to space or spacetype)
  src/energyplus/Test/SpaceInfiltrationDesignFlowRate_GTest.cpp
  src/energyplus/Test/SpaceInfiltrationEffectiveLeakageArea_GTest.cpp
  src/energyplus/Test/SpaceInfiltrationFlowCoefficient_GTest.cpp
Labels: Developer Issue, component - IDF Translation, Pull Request - Ready for CI

#4473 Fix #4472 - Modify Python in typemaps for `path` to accept string with Python 3 support
  ruby/test/Path_Test.rb
  src/utilities/core/Path.i
Labels: severity - Minor Bug, Pull Request - Ready for CI, component - Python bindings

#4447 Add ForwardTranslator options to the CLI `run` method
  CMakeLists.txt
  src/cli/openstudio_cli.rb
  src/utilities/filetypes/RunOptions.cpp
  src/utilities/filetypes/RunOptions.hpp
  src/utilities/filetypes/RunOptions_Impl.hpp
  src/utilities/filetypes/test/WorkflowJSON_GTest.cpp
Labels: component - CLI, Pull Request - Ready for CI
