Repository NREL/OpenStudio, pull requests merged in 2021-07, with the labels that each got.

#4371 Github Actions to publish python bindings to pypi when it's a release and testing worked
  .github/workflows/python_bindings.yml
  python/CMakeLists.txt
  python/find_pypi_tag.py
  python/test/test_find_pypi_tag.py
Labels: Developer Issue

#4369 #4214 Add in automated testing for 32/64 bit nuget package
  csharp/nuget_test/App.config
  csharp/nuget_test/README.md
  csharp/nuget_test/test_nuget.bat
  csharp/nuget_test/test_nuget.cs
Labels: Developer Issue

#4352 Fix #1571 - building.clone breaks space surface matching
  src/model/Building.cpp
  src/model/test/Building_GTest.cpp
Labels: Pull Request - Ready for CI, Ready for Merge, component - Model

#4378 Addresses #1515, Reverse Translator should retain thermal zone name from IDF instead of re-naming it
  src/energyplus/ReverseTranslator/ReverseTranslateZone.cpp
  src/energyplus/Test/ReverseTranslator_GTest.cpp
  src/energyplus/Test/ShadowCalculation_GTest.cpp
Labels: Enhancement Request, Pull Request - Ready for CI, component - IDF Translation

#4370 #4177 Non-zero exit code for openstudio-cli
  src/cli/openstudio_cli.rb
Labels: Pull Request - Ready for CI, component - CLI

#4365 Addresses #4364, Availability Schedule for DaylightingControl
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
  src/energyplus/Test/DaylightingControl_GTest.cpp
  src/model/ScheduleTypeRegistry.cpp
  src/model/ThermalZone.cpp
  src/model/ThermalZone.hpp
  src/model/ThermalZone_Impl.hpp
  src/model/test/ThermalZone_GTest.cpp
Labels: Enhancement Request, IDDChange, Pull Request - Ready for CI, component - Model

#4342 Fix #4327 - FanSystemModel electricPowerFraction should be optional
  src/energyplus/ForwardTranslator/ForwardTranslateFanSystemModel.cpp
  src/model/FanSystemModel.cpp
  src/model/FanSystemModel.hpp
  src/model/FanSystemModel_Impl.hpp
  src/model/test/FanSystemModel_GTest.cpp
Labels: APIChange, component - HVAC, severity - Normal Bug
