Repository NREL/OpenStudio, pull requests merged in 2022-01, with the labels that each got.

#4510 Addresses #4509, bad nodes created for AirLoopHVAC:UnitarySystem with only cooling coil and supplemental heating coil
  src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
  src/energyplus/Test/AirLoopHVACUnitarySystem_GTest.cpp
Labels: severity - Normal Bug, component - IDF Translation, Pull Request - Ready for CI

#4518 Bump openstudio-gems, conan-openstudio-ruby and add support for Apple M1
  CMakeLists.txt
  ConanInstall.cmake
  src/utilities/CMakeLists.txt
  src/utilities/core/UnzipFile.cpp
  src/utilities/core/ZipFile.cpp
Labels: Enhancement Request, Developer Issue, component - Conan

#4508 Addresses #4469, method to Translate ScheduleYear/ScheduleWeek to ScheduleRuleset
  src/energyplus/ReverseTranslator/ReverseTranslateScheduleDayInterval.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateScheduleYear.cpp
  src/energyplus/Test/ScheduleRuleset_GTest.cpp
Labels: Enhancement Request, component - IDF Translation, Pull Request - Ready for CI
