Repository NREL/OpenStudio, pull requests merged in 2022-09, with the labels that each got.

#4632 Remove deprecated methods for AirWallMaterial, Node, SizingSystem, ZoneAirMassFlowConservation
  developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_4_1_TBD.md
  developer/ruby/deprecated_methods.csv
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateAirWallMaterial.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateZoneAirMassFlowConservation.cpp
  src/energyplus/Test/AirWallMaterial_GTest.cpp
  src/energyplus/Test/AvailabilityManagerHighTemperatureTurnOff_GTest.cpp
  src/energyplus/Test/AvailabilityManagerHighTemperatureTurnOn_GTest.cpp
  src/energyplus/Test/AvailabilityManagerLowTemperatureTurnOff_GTest.cpp
  src/energyplus/Test/AvailabilityManagerLowTemperatureTurnOn_GTest.cpp
  src/energyplus/Test/EMS_GTest.cpp
  src/gbxml/ReverseTranslator.cpp
  src/model/AirLoopHVAC.cpp
  src/model/AirLoopHVAC.hpp
  src/model/AirTerminalSingleDuctVAVNoReheat.hpp
  src/model/AirWallMaterial.cpp
  src/model/AirWallMaterial.hpp
  src/model/AirWallMaterial_Impl.hpp
  src/model/AvailabilityManagerNightCycle.cpp
  src/model/AvailabilityManagerNightCycle.hpp
  src/model/AvailabilityManagerNightCycle_Impl.hpp
  src/model/CMakeLists.txt
  src/model/ConcreteModelObjects.hpp
  src/model/FloorspaceReverseTranslator.cpp
  src/model/Model.cpp
  src/model/ModelResources.i
  src/model/Node.cpp
  src/model/Node.hpp
  src/model/Node_Impl.hpp
  src/model/PlanarSurface.cpp
  src/model/PlanarSurface.hpp
  src/model/PlantLoop.cpp
  src/model/PlantLoop.hpp
  src/model/SizingSystem.cpp
  src/model/SizingSystem.hpp
  src/model/ThreeJSReverseTranslator.cpp
  src/model/ZoneAirMassFlowConservation.cpp
  src/model/ZoneAirMassFlowConservation.hpp
  src/model/ZoneAirMassFlowConservation_Impl.hpp
  src/model/ZoneVentilationDesignFlowRate.cpp
  src/model/ZoneVentilationDesignFlowRate.hpp
  src/model/ZoneVentilationDesignFlowRate_Impl.hpp
  src/model/test/AirflowNetworkSurface_GTest.cpp
  src/model/test/Construction_GTest.cpp
  src/model/test/EnergyManagementSystemConstructionIndexVariable_GTest.cpp
  src/model/test/ModelPartitionMaterial_GTest.cpp
  src/model/test/Node_GTest.cpp
  src/model/test/SetpointManagerWarmest_GTest.cpp
  src/model/test/Surface_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/VersionTranslator.hpp
  src/osversion/test/3_4_1/test_vt_AirWallMaterial.osm
  src/osversion/test/3_4_1/test_vt_AirWallMaterial.rb
  src/osversion/test/VersionTranslator_GTest.cpp
  src/utilities/idd/Test/IddFactory_GTest.cpp
Labels: component - Model, Pull Request - Ready for CI, APIChange

#4669 #4668 - Wrap E+ 22.2 new People fields
  resources/energyplus/ProposedEnergy+.idd
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslatePeople.cpp
  src/energyplus/ReverseTranslator/ReverseTranslatePeople.cpp
  src/energyplus/Test/People_GTest.cpp
  src/epjson/test/epJSONFixture.cpp
  src/epjson/test/epJSONFixture.hpp
  src/epjson/test/epJSONTranslator_GTest.cpp
  src/model/People.cpp
  src/model/People.hpp
  src/model/People_Impl.hpp
  src/model/ScheduleTypeRegistry.cpp
Labels: Enhancement Request

#4652 Addresses #4647, wrap the E+ Table:Lookup, Table:IndependentVariableList, and Table:IndependentVariable objects
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateTableIndependentVariable.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateTableLookup.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateTableMultiVariableLookup.cpp
  src/energyplus/ReverseTranslator.cpp
  src/energyplus/ReverseTranslator.hpp
  src/energyplus/ReverseTranslator/ReverseTranslateTableIndependentVariable.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateTableLookup.cpp
  src/energyplus/Test/TableLookup_GTest.cpp
  src/energyplus/Test/TableMultiVariableLookup_GTest.cpp
  src/model/CMakeLists.txt
  src/model/CoilCoolingFourPipeBeam.cpp
  src/model/CoilHeatingFourPipeBeam.cpp
  src/model/ConcreteModelObjects.hpp
  src/model/Model.cpp
  src/model/ModelResources.i
  src/model/TableIndependentVariable.cpp
  src/model/TableIndependentVariable.hpp
  src/model/TableIndependentVariable_Impl.hpp
  src/model/TableLookup.cpp
  src/model/TableLookup.hpp
  src/model/TableLookup_Impl.hpp
  src/model/TableMultiVariableLookup.cpp
  src/model/TableMultiVariableLookup.hpp
  src/model/test/CoilCoolingFourPipeBeam_GTest.cpp
  src/model/test/CoilHeatingFourPipeBeam_GTest.cpp
  src/model/test/CoilWaterHeatingAirToWaterHeatPump_GTest.cpp
  src/model/test/TableIndependentVariable_GTest.cpp
  src/model/test/TableLookup_GTest.cpp
  src/model/test/TableMultiVariableLookup_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/VersionTranslator.hpp
  src/osversion/test/3_4_1/test_vt_TableMultiVariableLookup.rb
  src/osversion/test/3_4_1/test_vt_TableMultiVariableLookup_oneDim.osm
  src/osversion/test/3_4_1/test_vt_TableMultiVariableLookup_twoDims.osm
  src/osversion/test/VersionTranslator_GTest.cpp
  src/sdd/ForwardTranslator.cpp
  src/sdd/MapHVAC.cpp
Labels: Enhancement Request, component - Model, Pull Request - Ready for CI

#4679 Remove cruft
  .decent_ci-Linux.yaml
  .decent_ci-MacOS.yaml
  .decent_ci-Windows.yaml
  .decent_ci.yaml
  .gitlab-ci.yml
  CMakeLists.txt
  INSTALL.md
  dependencies/Boost/fchmodat.patch
  dependencies/Boost/gcc_5_no_cxx11.patch
  dependencies/Boost/transform_width.diff
  dependencies/Boost/xcode_51.patch
  dependencies/GoogleTest/CMakeLists.txt
  dependencies/qt/build_shared_qt.bat.in
  dependencies/qt/build_static_qt.bat.in
  dependencies/qt/qmacstyle_mac.patch
  dependencies/ruby/.gitignore
  dependencies/ruby/i386-mingw32.patch
  dependencies/ruby/notes.md
  dependencies/ruby/x64-mingw32.patch
  java/CMakeLists.txt
  java/README.md
  java/TestOpenStudio.java
  osruby_config.h
  v8-node/CMakeLists.txt
  v8-node/OpenStudio.js
  v8-node/README.txt
  v8-node/engine_test.js
  v8-node/jasmine/runmanager/createmodel_spec.js
  v8-node/jasmine/runmanager/simulation_spec.js
  v8-node/run_simulation.js
  v8-node/test/exception_test.js
  v8-node/test/inheritance2_test.js
  v8-node/test/inheritance3_test.js
  v8-node/test/inheritance_test.js
  v8-node/test/optional_test.js
  v8-node/test/returntypesfromothermodules_test.js
  v8-node/test/simple_test.js
  v8-node/test/simulation_test.js
Labels: Developer Issue, Pull Request - Ready for CI

#4672 Fix #4645 - Update FT for space-level infiltration/ventilation objects (E+ 22.2.0-IOFreeze)
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipment.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipmentITEAirCooled.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateGasEquipment.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateHotWaterEquipment.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateLights.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateLuminaire.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateOtherEquipment.cpp
  src/energyplus/ForwardTranslator/ForwardTranslatePeople.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSpaceInfiltrationDesignFlowRate.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSpaceInfiltrationEffectiveLeakageArea.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSpaceInfiltrationFlowCoefficient.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSpaceType.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSteamEquipment.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSwimmingPoolIndoor.cpp
  src/energyplus/Test/SpaceInfiltrationDesignFlowRate_GTest.cpp
  src/energyplus/Test/SpaceInfiltrationEffectiveLeakageArea_GTest.cpp
  src/energyplus/Test/SpaceInfiltrationFlowCoefficient_GTest.cpp
Labels: Enhancement Request, component - IDF Translation, Pull Request - Ready for CI

#4681 Fix glass U factor sql error
  CMakeLists.txt
  src/model/SubSurface.cpp
  src/model/Surface.cpp
  src/model/test/SubSurface_GTest.cpp
  src/model/test/Surface_GTest.cpp
Labels: severity - Normal Bug, component - Model, Pull Request - Ready for CI

#4661 Volume, CeilingHeight, FloorArea for Space object
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateSpace.cpp
  src/model/Space.cpp
  src/model/Space.hpp
  src/model/Space_Impl.hpp
  src/model/test/Space_GTest.cpp
Labels: Pull Request - Ready for CI, IDDChange

#4660 Fix #4120 - set boost's visibility to global/default instead of hidden
  ConanInstall.cmake
  src/utilities/core/PathHelpers.cpp
Labels: Developer Issue, Pull Request - Ready for CI

#4665 New 2017 and 2023 flow rate fields
  developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_4_1_TBD.md
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingDXCurveFitSpeed.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingDXMultiSpeed.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingDXSingleSpeed.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingDXMultiSpeed.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingDXSingleSpeed.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateCoilCoolingDXCurveFitSpeed.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateCoilCoolingDXSingleSpeed.cpp
  src/energyplus/Test/CoilCoolingDXCurveFitSpeed_GTest.cpp
  src/energyplus/Test/CoilCoolingDXMultiSpeed_GTest.cpp
  src/energyplus/Test/CoilHeatingDXMultiSpeed_GTest.cpp
  src/model/CoilCoolingDXCurveFitSpeed.cpp
  src/model/CoilCoolingDXCurveFitSpeed.hpp
  src/model/CoilCoolingDXCurveFitSpeed_Impl.hpp
  src/model/CoilCoolingDXMultiSpeedStageData.cpp
  src/model/CoilCoolingDXMultiSpeedStageData.hpp
  src/model/CoilCoolingDXMultiSpeedStageData_Impl.hpp
  src/model/CoilCoolingDXSingleSpeed.cpp
  src/model/CoilCoolingDXSingleSpeed.hpp
  src/model/CoilCoolingDXSingleSpeed_Impl.hpp
  src/model/CoilHeatingDXMultiSpeedStageData.cpp
  src/model/CoilHeatingDXMultiSpeedStageData.hpp
  src/model/CoilHeatingDXMultiSpeedStageData_Impl.hpp
  src/model/CoilHeatingDXSingleSpeed.cpp
  src/model/CoilHeatingDXSingleSpeed.hpp
  src/model/CoilHeatingDXSingleSpeed_Impl.hpp
  src/model/test/CoilCoolingDXCurveFitSpeed_GTest.cpp
  src/model/test/CoilCoolingDXMultiSpeedStageData_GTest.cpp
  src/model/test/CoilCoolingDXSingleSpeed_GTest.cpp
  src/model/test/CoilHeatingDXMultiSpeedStageData_GTest.cpp
  src/model/test/CoilHeatingDXSingleSpeed_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/test/3_5_0/test_vt_CoilCoolingDXCurveFitSpeed.osm
  src/osversion/test/3_5_0/test_vt_CoilCoolingDXCurveFitSpeed.rb
  src/osversion/test/3_5_0/test_vt_CoilCoolingDXMultiSpeedStageData.osm
  src/osversion/test/3_5_0/test_vt_CoilCoolingDXMultiSpeedStageData.rb
  src/osversion/test/3_5_0/test_vt_CoilCoolingDXSingleSpeed.osm
  src/osversion/test/3_5_0/test_vt_CoilCoolingDXSingleSpeed.rb
  src/osversion/test/3_5_0/test_vt_CoilHeatingDXMultiSpeedStageData.osm
  src/osversion/test/3_5_0/test_vt_CoilHeatingDXMultiSpeedStageData.rb
  src/osversion/test/3_5_0/test_vt_CoilHeatingDXSingleSpeed.osm
  src/osversion/test/3_5_0/test_vt_CoilHeatingDXSingleSpeed.rb
  src/osversion/test/VersionTranslator_GTest.cpp
Labels: Pull Request - Ready for CI, IDDChange

#4671 New Coil:*:WaterToAirHeatPump:EquationFit fields
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingWaterToAirHeatPumpEquationFit.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingWaterToAirHeatPumpEquationFit.cpp
  src/energyplus/Test/ZoneHVACWaterToAirHeatPump_GTest.cpp
  src/model/CoilCoolingWaterToAirHeatPumpEquationFit.cpp
  src/model/CoilCoolingWaterToAirHeatPumpEquationFit.hpp
  src/model/CoilCoolingWaterToAirHeatPumpEquationFit_Impl.hpp
  src/model/CoilHeatingWaterToAirHeatPumpEquationFit.cpp
  src/model/CoilHeatingWaterToAirHeatPumpEquationFit.hpp
  src/model/CoilHeatingWaterToAirHeatPumpEquationFit_Impl.hpp
  src/model/test/CoilCoolingWaterToAirHeatPumpEquationFit_GTest.cpp
  src/model/test/CoilHeatingWaterToAirHeatPumpEquationFit_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/test/3_5_0/test_vt_CoilCoolingWaterToAirHeatPumpEquationFit.osm
  src/osversion/test/3_5_0/test_vt_CoilHeatingWaterToAirHeatPumpEquationFit.osm
  src/osversion/test/3_5_0/test_vt_EquationFitCoils.rb
  src/osversion/test/VersionTranslator_GTest.cpp
Labels: Pull Request - Ready for CI, IDDChange

#4677 Fix #4675 - E+ 22.2.0 - Sizing:Zone has new fields
  resources/energyplus/ProposedEnergy+.idd
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateSizingZone.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateSizingZone.cpp
  src/energyplus/Test/SizingZone_GTest.cpp
  src/model/ScheduleTypeRegistry.cpp
  src/model/SizingZone.cpp
  src/model/SizingZone.hpp
  src/model/SizingZone_Impl.hpp
  src/model/test/SizingZone_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/test/3_5_0/test_vt_SizingZone.osm
  src/osversion/test/3_5_0/test_vt_SizingZone.rb
  src/osversion/test/VersionTranslator_GTest.cpp
Labels: Enhancement Request, component - Model, component - IDF Translation, component - Version Translator, Pull Request - Ready for CI, IDDChange

#4691 Followup to #4575
  src/model/CoilCoolingDXSingleSpeed.cpp
  src/model/CoilCoolingDXTwoSpeed.cpp
  src/model/test/CoilCoolingDXTwoSpeed_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/test/3_4_1/test_vt_CoilCoolingDXSingleSpeed.osm
  src/osversion/test/3_4_1/test_vt_CoilCoolingDXSingleSpeed.rb
  src/osversion/test/VersionTranslator_GTest.cpp
Labels: component - Model, Pull Request - Ready for CI

#4662 Support CoilCoolingDX on ZoneHVAC, CoilSystem, Desuperheater
  resources/energyplus/ProposedEnergy+.idd
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingDX.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingDesuperheater.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilSystemCoolingDXHeatExchangerAssisted.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilWaterHeatingDesuperheater.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACPackagedTerminalAirConditioner.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACPackagedTerminalHeatPump.cpp
  src/energyplus/Test/CoilCoolingDX_GTest.cpp
  src/energyplus/Test/CoilHeatingDesuperheater_GTest.cpp
  src/energyplus/Test/CoilWaterHeatingDesuperheater_GTest.cpp
  src/energyplus/Test/ZoneHVACPackagedTerminalAirConditioner_GTest.cpp
  src/energyplus/Test/ZoneHVACPackagedTerminalHeatPump_GTest.cpp
  src/model/CoilCoolingDX.cpp
  src/model/CoilCoolingDX_Impl.hpp
  src/model/ZoneHVACPackagedTerminalAirConditioner.cpp
  src/model/ZoneHVACPackagedTerminalHeatPump.cpp
  src/model/test/CoilCoolingDX_GTest.cpp
Labels: Pull Request - Ready for CI, IDDChange

#4687 Fix #4656 - E+ 22.2.0: Wrap Chiller:Electric:ASHRAE205
  resources/CMakeLists.txt
  resources/energyplus/ProposedEnergy+.idd
  resources/model/A205ExampleChiller.RS0001.a205.cbor
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateChillerElectricASHRAE205.cpp
  src/energyplus/ForwardTranslator/ForwardTranslatePlantEquipmentOperationSchemes.cpp
  src/energyplus/ForwardTranslator/ForwardTranslatePlantLoop.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateSizingPlant.cpp
  src/energyplus/ReverseTranslator.cpp
  src/energyplus/ReverseTranslator.hpp
  src/energyplus/ReverseTranslator/ReverseTranslateChillerElectricASHRAE205.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateCoilCoolingDX.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateElectricLoadCenterStorageConverter.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateElectricLoadCenterStorageLiIonNMCBattery.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateElectricLoadCenterStorageSimple.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateFanSystemModel.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateRefrigerationCase.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateZoneCrossMixing.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateZoneMixing.cpp
  src/energyplus/Test/ChillerElectricASHRAE205_GTest.cpp
  src/model/CMakeLists.txt
  src/model/ChillerElectricASHRAE205.cpp
  src/model/ChillerElectricASHRAE205.hpp
  src/model/ChillerElectricASHRAE205_Impl.hpp
  src/model/ConcreteModelObjects.hpp
  src/model/ExternalFile.cpp
  src/model/ExternalFile.hpp
  src/model/ExternalFile_Impl.hpp
  src/model/Loop.cpp
  src/model/Model.cpp
  src/model/ModelHVAC.i
  src/model/ScheduleTypeRegistry.cpp
  src/model/WaterToWaterComponent.cpp
  src/model/WaterToWaterComponent_Impl.hpp
  src/model/test/ChillerElectricASHRAE205_GTest.cpp
Labels: Enhancement Request, component - HVAC, component - Model, IDDChange

#4697 Volume, CeilingHeight, FloorArea for Space object, try 2
  src/energyplus/ForwardTranslator/ForwardTranslateSpace.cpp
  src/energyplus/Test/Space_GTest.cpp
Labels: Pull Request - Ready for CI

#4683 #4663 #4664 - Fix CoilCoolingDXMultiSpeed::clone and extend testing for AirLoopHVAC::clone
  src/model/CoilCoolingDXMultiSpeed.cpp
  src/model/test/AirLoopHVAC_GTest.cpp
  src/model/test/CoilCoolingDXMultiSpeed_GTest.cpp
Labels: severity - Normal Bug, component - Model, Pull Request - Ready for CI

#4685 Address #4630, wrap Output:Schedules and Output:Constructions objects
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateOutputConstructions.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateOutputSchedules.cpp
  src/energyplus/ReverseTranslator.cpp
  src/energyplus/ReverseTranslator.hpp
  src/energyplus/ReverseTranslator/ReverseTranslateOutputConstructions.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateOutputSchedules.cpp
  src/energyplus/Test/OutputConstructions_GTest.cpp
  src/energyplus/Test/OutputSchedules_GTest.cpp
  src/model/CMakeLists.txt
  src/model/ConcreteModelObjects.hpp
  src/model/Model.cpp
  src/model/Model.hpp
  src/model/ModelCore.i
  src/model/ModelSimulation.i
  src/model/Model_Impl.hpp
  src/model/OutputConstructions.cpp
  src/model/OutputConstructions.hpp
  src/model/OutputConstructions_Impl.hpp
  src/model/OutputSchedules.cpp
  src/model/OutputSchedules.hpp
  src/model/OutputSchedules_Impl.hpp
  src/model/test/OutputConstructions_GTest.cpp
  src/model/test/OutputSchedules_GTest.cpp
  src/model/test/UniqueModelObject_GTest.cpp
Labels: Enhancement Request, component - Model, Pull Request - Ready for CI

#4702 Mod to Python Engine
  python/module/CMakeLists.txt
  resources/Examples/compact_osw/measures/IncreaseRoofRValuePython/measure.py
  src/cli/CMakeLists.txt
  src/measure/EnergyPlusMeasure.cpp
  src/measure/EnergyPlusMeasure.hpp
  src/measure/Measure.i
  src/measure/ModelMeasure.cpp
  src/measure/ModelMeasure.hpp
  src/measure/OSArgument.hpp
  src/measure/OSMeasure.cpp
  src/measure/ReportingMeasure.cpp
  src/measure/ReportingMeasure.hpp
  src/model/Model.i
  src/model/ModelCore.i
  src/utilities/Utilities.i
  src/utilities/filetypes/WorkflowStepResult.cpp
  src/utilities/idf/Idf.i
  src/utilities/idf/Workspace.hpp
  src/workflow/OSWorkflow.cpp
  src/workflow/OSWorkflow.hpp
Labels: Developer Issue
