Repository NREL/OpenStudio, pull requests merged in 2023-10, with the labels that each got.

#4998 Fix #4997 - Add Workspace casting methods in python bindings
  src/model/ModelCore.i
Labels: component - Model, Pull Request - Ready for CI, component - Python bindings

#5000 Fix #4999 - Change latent degration constructor defaults for CoilCoolingWaterToAirHeatPump:XXXX
  src/model/CoilCoolingWaterToAirHeatPumpEquationFit.cpp
  src/model/CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit.cpp
  src/model/test/CoilCoolingWaterToAirHeatPumpEquationFit_GTest.cpp
  src/model/test/CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/test/VersionTranslator_GTest.cpp
Labels: component - Model, component - Version Translator, Pull Request - Ready for CI

#4987 Fix #4979 - Add operator __bool__ for optional in python bindings
  python/CMakeLists.txt
  python/Pytest.cmake
  python/test/CMakeLists.txt
  python/test/test_usability.py
  src/utilities/core/CommonImport.i
Labels: Pull Request - Ready for CI

#4996 [Partial] Update openstudio gems with new TBD and openstudio extensio…
  CMakeLists.txt
Labels: Pull Request - Ready for CI, component - Ruby bindings

#5003 Allow edges to have same surface on both sides
  src/cli/main.cpp
  src/utilities/geometry/Polyhedron.cpp
  src/utilities/geometry/Test/Polyhedron_GTest.cpp
Labels: component - Utilities Geometry, Pull Request - Ready for CI

#5006 Make the "labs" cli implementation the default
  src/cli/CMakeLists.txt
  src/cli/main.cpp
  src/cli/test/execute_python_script_with_numpy.py
  src/cli/test/run_test_logger.py
  src/cli/test/test_loglevel.py
Labels: Pull Request - Ready for CI

#5010 [internal] Schedule:File relative paths mod
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateScheduleFile.cpp
  src/energyplus/Test/ScheduleInterval_GTest.cpp
  src/model/ScheduleFile.cpp
  src/model/ScheduleFile.hpp
  src/model/ScheduleFile_Impl.hpp
  src/model/test/ScheduleInterval_GTest.cpp
Labels: Developer Issue
