Repository NREL/OpenStudio, pull requests merged in 2023-04, with the labels that each got.

#4849 Update standards to 0.3.1-rc2 and tbd gem to 3.2.2
  CMakeLists.txt
Labels: Pull Request - Ready for CI

#4851 Recent clang throws on these functions. codecvt_utf8_utf16 is deprecated
  src/energyplus/Test/ChillerElectricASHRAE205_GTest.cpp
  src/utilities/core/String.cpp
Labels: Developer Issue, Pull Request - Ready for CI

#4854 Fix #4853 - RemoteBCLTest2
  src/utilities/bcl/test/BCL_GTest.cpp
Labels: Developer Issue, component - Testing, Pull Request - Ready for CI

#4861 update to latest gems including standards release v0.4.0
  CMakeLists.txt
Labels: component - CLI, Pull Request - Ready for CI

#4867 Update gems for darwin arm64
  CMakeLists.txt
Labels: Developer Issue

#4857 Schedule:File ctor with path
  src/model/ExternalFile.cpp
  src/model/ExternalFile.hpp
  src/model/ScheduleFile.cpp
  src/model/ScheduleFile.hpp
  src/model/test/ScheduleInterval_GTest.cpp
Labels: severity - Normal Bug, Enhancement Request, component - Model, Pull Request - Ready for CI

#4852 Fix #4847 - OpenStudio logging behaves differently on Windows/Linux
  src/cli/CMakeLists.txt
  src/cli/main.cpp
  src/cli/test/logger_test.py
  src/cli/test/logger_test.rb
  src/cli/test/run_test_logger.py
Labels: component - CLI, Pull Request - Ready for CI

#4871 update gems and set addressable gem to use v2.8.1
  CMakeLists.txt
Labels: Pull Request - Ready for CI
