Repository NREL/OpenStudio, pull requests merged in 2024-11, with the labels that each got.

#5285 Update os gems for openstudio.
  CMakeLists.txt
Labels: Pull Request - Ready for CI

#5284 Correct misspelling of openstudioalfalfa python module
  python/module/openstudio.py
Labels: Pull Request - Ready for CI

#5293 Fix namesapce for types in GTest
  src/alfalfa/test/AlfalfaJSON_GTest.cpp
Labels: Pull Request - Ready for CI

#5291 Try to fix Broken C# bindings workflow due to Alfalfa addition
  .github/workflows/buildCSharp.yml
  ProjectMacros.cmake
  csharp/CMakeLists.txt
  src/alfalfa/Alfalfa.i
  src/alfalfa/AlfalfaActuator.hpp
  src/alfalfa/AlfalfaComponent.cpp
  src/alfalfa/AlfalfaComponent.hpp
  src/alfalfa/AlfalfaComponentBase.cpp
  src/alfalfa/AlfalfaComponentBase.hpp
  src/alfalfa/AlfalfaConstant.hpp
  src/alfalfa/AlfalfaGlobalVariable.hpp
  src/alfalfa/AlfalfaMeter.hpp
  src/alfalfa/AlfalfaOutputVariable.hpp
  src/alfalfa/CMakeLists.txt
  src/alfalfa/ComponentBase.cpp
  src/alfalfa/test/AlfalfaJSON_GTest.cpp
  src/gltf/GltfMaterialData.cpp
  src/gltf/GltfMaterialData.hpp
  src/measure/CMakeLists.txt
  src/measure/Measure.i
  src/utilities/data/Data.i
  src/utilities/data/DataEnums.hpp
Labels: Developer Issue, component - C#, Pull Request - Ready for CI

#5296 Relax Alfalfa Point ID Requirements
  src/alfalfa/AlfalfaJSON.cpp
  src/alfalfa/AlfalfaPoint.cpp
  src/alfalfa/AlfalfaPoint.hpp
  src/alfalfa/AlfalfaPoint_Impl.hpp
  src/alfalfa/test/AlfalfaJSON_GTest.cpp
Labels: Pull Request - Ready for CI

#5295 Fix #5233 - Validate OSW measures before running
  resources/workflow/invalid_measures/missing_a_measure.osw
  resources/workflow/invalid_measures/unloadable_measure.osw
  resources/workflow/invalid_measures/wrong_measure_type_order.osw
  resources/workflow/measures/FakeModelMeasure/measure.rb
  resources/workflow/measures/FakeModelMeasure/measure.xml
  resources/workflow/measures/UnloadableMeasure/README.md
  resources/workflow/measures/UnloadableMeasure/measure.rb
  src/cli/CMakeLists.txt
  src/utilities/filetypes/WorkflowJSON.cpp
  src/utilities/filetypes/WorkflowJSON.hpp
  src/utilities/filetypes/WorkflowJSON_Impl.hpp
  src/utilities/filetypes/test/WorkflowJSON_GTest.cpp
  src/workflow/RunInitialization.cpp
Labels: component - Workflow, Pull Request - Ready for CI

#5298 Fix Ruby/Python SWIG API when type is AlfalfaComponent
  resources/Examples/compact_osw/measures/AlfalfaEPlusPython/measure.py
  resources/Examples/compact_osw/measures/AlfalfaEPlusRuby/measure.rb
  src/alfalfa/Alfalfa.i
  src/alfalfa/AlfalfaComponent.hpp
  src/alfalfa/test/AlfalfaJSON_GTest.cpp
Labels: Pull Request - Ready for CI

#5288 Fixup the python bindings workflow, add python 3.13 for windows, and use os.add_dll_directory for windows
  .github/workflows/python_bindings.yml
  python/engine/PythonEngine.cpp
  python/module/openstudio.py
Labels: Developer Issue, Pull Request - Ready for CI, component - Python bindings

#5301 Fix #5249 - Implement a CLI `pip_list` subcommand similar to the ruby `gem_list` one
  src/cli/UpdateCommand.cpp
  src/cli/UpdateCommand.hpp
  src/cli/main.cpp
Labels: component - CLI, Pull Request - Ready for CI, component - Python bindings
