Repository NREL/OpenStudio, pull requests merged in 2024-03, with the labels that each got.

#5099 v24.1.0-IOFreeze: HeatExchangerAirToAirSensibleAndLatent
  resources/energyplus/ProposedEnergy+.idd
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateHeatExchangerAirToAirSensibleAndLatent.cpp
  src/model/HeatExchangerAirToAirSensibleAndLatent.cpp
  src/model/HeatExchangerAirToAirSensibleAndLatent.hpp
  src/model/HeatExchangerAirToAirSensibleAndLatent_Impl.hpp
  src/model/test/HeatExchangerAirToAirSensibleAndLatent_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/VersionTranslator.hpp
  src/osversion/test/3_8_0/test_vt_HeatExchangerAirToAirSensibleAndLatent.osm
  src/osversion/test/3_8_0/test_vt_HeatExchangerAirToAirSensibleAndLatent.rb
  src/osversion/test/VersionTranslator_GTest.cpp
  src/sdd/MapHVAC.cpp
Labels: Pull Request - Ready for CI, IDDChange

#5096 v24.1.0-IOFreeze: No Load Supply Air Flow Rate Control Set To Low Speed
  resources/energyplus/ProposedEnergy+.idd
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACPackagedTerminalAirConditioner.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACPackagedTerminalHeatPump.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACWaterToAirHeatPump.cpp
  src/energyplus/Test/AirLoopHVACUnitarySystem_GTest.cpp
  src/energyplus/Test/ZoneHVACPackagedTerminalAirConditioner_GTest.cpp
  src/energyplus/Test/ZoneHVACPackagedTerminalHeatPump_GTest.cpp
  src/energyplus/Test/ZoneHVACWaterToAirHeatPump_GTest.cpp
  src/model/AirLoopHVACUnitarySystem.cpp
  src/model/AirLoopHVACUnitarySystem.hpp
  src/model/AirLoopHVACUnitarySystem_Impl.hpp
  src/model/ZoneHVACPackagedTerminalAirConditioner.cpp
  src/model/ZoneHVACPackagedTerminalAirConditioner.hpp
  src/model/ZoneHVACPackagedTerminalAirConditioner_Impl.hpp
  src/model/ZoneHVACPackagedTerminalHeatPump.cpp
  src/model/ZoneHVACPackagedTerminalHeatPump.hpp
  src/model/ZoneHVACPackagedTerminalHeatPump_Impl.hpp
  src/model/ZoneHVACWaterToAirHeatPump.cpp
  src/model/ZoneHVACWaterToAirHeatPump.hpp
  src/model/ZoneHVACWaterToAirHeatPump_Impl.hpp
  src/model/test/AirLoopHVACUnitarySystem_GTest.cpp
  src/model/test/ZoneHVACPackagedTerminalAirConditioner_GTest.cpp
  src/model/test/ZoneHVACPackagedTerminalHeatPump_GTest.cpp
  src/model/test/ZoneHVACWaterToAirHeatPump_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/test/3_8_0/test_vt_NoLoadSupplyAirFlowRateControlSetToLowSpeed.osm
  src/osversion/test/3_8_0/test_vt_NoLoadSupplyAirFlowRateControlSetToLowSpeed.rb
  src/osversion/test/VersionTranslator_GTest.cpp
Labels: Pull Request - Ready for CI, IDDChange

#5100 v24.1.0-IOFreeze: PeopleDefinition's EnclosureAveraged key
  resources/model/OpenStudio.idd
  src/model/PeopleDefinition.cpp
  src/model/test/People_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/test/3_8_0/test_vt_PeopleDefinition.osm
  src/osversion/test/3_8_0/test_vt_PeopleDefinition.rb
  src/osversion/test/VersionTranslator_GTest.cpp
Labels: Pull Request - Ready for CI, IDDChange

#5109 Fix #5108 - quote call to ExpandObjects for paths with spaces
  src/workflow/RunEnergyPlus.cpp
Labels: severity - Normal Bug, component - CLI, component - Workflow, Pull Request - Ready for CI

#5105 Fix #5103 - ElectricEquipmentITEAirCooled / ElectricEquipmentITEAirCooledDefinition - align objects with other SpaceLoads
  developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_8_0_TBD.md
  developer/ruby/DeprecatedMethods.rb
  developer/ruby/deprecated_methods.csv
  resources/model/OpenStudio.idd
  src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipmentITEAirCooled.cpp
  src/energyplus/Test/ElectricEquipmentITEAirCooled_GTest.cpp
  src/model/ElectricEquipmentITEAirCooled.cpp
  src/model/ElectricEquipmentITEAirCooled.hpp
  src/model/ElectricEquipmentITEAirCooledDefinition.cpp
  src/model/ElectricEquipmentITEAirCooledDefinition.hpp
  src/model/ElectricEquipmentITEAirCooledDefinition_Impl.hpp
  src/model/ElectricEquipmentITEAirCooled_Impl.hpp
  src/model/Space.cpp
  src/model/SpaceType.cpp
  src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp
Labels: component - Model, Pull Request - Ready for CI, APIChange

#5117 Fix #5116 - Annoying FT warnings for always XX Scheduled missing the schedule type limits object
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/Test/ForwardTranslator_GTest.cpp
Labels: severity - Normal Bug, component - IDF Translation, Pull Request - Ready for CI

#5130 Update to E+ v24.1.0-RC3
  CMakeLists.txt
Labels: Pull Request - Ready for CI

#5059 Wrap Coil:Cooling:DX:SingleSpeed:ThermalStorage
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingDXSingleSpeedThermalStorage.cpp
  src/energyplus/Test/CoilCoolingDXSingleSpeedThermalStorage_GTest.cpp
  src/model/CMakeLists.txt
  src/model/CoilCoolingDXSingleSpeedThermalStorage.cpp
  src/model/CoilCoolingDXSingleSpeedThermalStorage.hpp
  src/model/CoilCoolingDXSingleSpeedThermalStorage_Impl.hpp
  src/model/ConcreteModelObjects.hpp
  src/model/Model.cpp
  src/model/ModelStraightComponent.i
  src/model/ScheduleTypeRegistry.cpp
  src/model/test/CoilCoolingDXSingleSpeedThermalStorage_GTest.cpp
Labels: Enhancement Request, component - HVAC, component - Model, Pull Request - Ready for CI, IDDChange

#5114 Incorrect FT of ScheduleRules at end of year
  src/energyplus/ForwardTranslator/ForwardTranslateScheduleRuleset.cpp
  src/energyplus/Test/ScheduleRuleset_GTest.cpp
Labels: severity - Normal Bug, component - IDF Translation, Pull Request - Ready for CI

#5126 Fix #5125 - Add versionModified, repo, org, releaseTag to BCLSearchResult
  src/utilities/bcl/BCL.cpp
  src/utilities/bcl/BCL.hpp
  src/utilities/bcl/BCLXML.cpp
  src/utilities/bcl/test/BCL_GTest.cpp
Labels: component - Measures, component - Utilities Other, Pull Request - Ready for CI

#5119 4847 logger singleton 3.1
  ProjectMacros.cmake
  python/engine/CMakeLists.txt
  src/airflow/Airflow.i
  src/cli/CMakeLists.txt
  src/cli/main.cpp
  src/cli/test/Logger_GTest.cpp
  src/energyplus/EnergyPlus.i
  src/epjson/epJSON.i
  src/gbxml/gbXML.i
  src/gltf/Gltf.i
  src/isomodel/ISOModel.i
  src/measure/Measure.i
  src/model/ModelGeometry.i
  src/model/Model_Common_Include.i
  src/osversion/OSVersion.i
  src/radiance/AnnualIlluminanceMap.i
  src/radiance/HeaderInfo.i
  src/radiance/Radiance.i
  src/sdd/SDD.i
  src/utilities/Utilities.i
  src/utilities/UtilitiesBCL.i
  src/utilities/UtilitiesCore.i
  src/utilities/UtilitiesData.i
  src/utilities/UtilitiesFileTypes.i
  src/utilities/UtilitiesGeometry.i
  src/utilities/UtilitiesIdd.i
  src/utilities/UtilitiesIdf.i
  src/utilities/UtilitiesPlot.i
  src/utilities/UtilitiesSql.i
  src/utilities/UtilitiesTime.i
  src/utilities/UtilitiesUnits.i
  src/utilities/UtilitiesXML.i
  src/utilities/core/LogSink.hpp
  src/utilities/core/Logger.cpp
  src/utilities/core/Logger.hpp
  src/utilities/core/Logger.i
Labels: Pull Request - Ready for CI

#5129 Fix #5128 - Properly remove old components/measures when updating
  src/utilities/bcl/LocalBCL.cpp
  src/utilities/bcl/LocalBCL.hpp
  src/utilities/bcl/RemoteBCL.cpp
Labels: component - Measures, Pull Request - Ready for CI
