Repository NREL/OpenStudio, pull requests merged in 2024-04, with the labels that each got.

#5131 Update to EnergyPlus v24.1.0 official
  CMakeLists.txt
Labels: Pull Request - Ready for CI

#5118 Fix #1472 - Respect user's SimulationControl choices and move smart defaults to the modelObject
  src/energyplus/ForwardTranslator/ForwardTranslateSimulationControl.cpp
  src/model/SimulationControl.cpp
  src/model/SimulationControl.hpp
  src/model/test/SimulationControl_GTest.cpp
Labels: component - Model, component - IDF Translation, Pull Request - Ready for CI

#5106 Fix #5101 - Update monthly reports for DistrictHeatingWater
  developer/ruby/GeneratePreProcessMonthlyReports.rb
  src/workflow/CMakeLists.txt
  src/workflow/RunPreProcessMonthlyReports.hpp
  src/workflow/test/RunPreProcessMonthlyReports_GTest.cpp
Labels: severity - Normal Bug, component - Measures, component - IDF Translation, component - Workflow

#5122 #5121 - Extensible Groups problems in ModelObject/WorkspaceObject
  src/model/test/ZoneHVACEquipmentList_GTest.cpp
  src/utilities/idf/IdfExtensibleGroup.cpp
  src/utilities/idf/IdfExtensibleGroup.hpp
  src/utilities/idf/IdfObject.cpp
  src/utilities/idf/IdfObject.hpp
  src/utilities/idf/IdfObject_Impl.hpp
  src/utilities/idf/Test/ExtensibleGroup_GTest.cpp
  src/utilities/idf/Test/WorkspaceObject_GTest.cpp
  src/utilities/idf/WorkspaceExtensibleGroup.cpp
  src/utilities/idf/WorkspaceExtensibleGroup.hpp
  src/utilities/idf/WorkspaceObject.cpp
  src/utilities/idf/WorkspaceObject.hpp
  src/utilities/idf/WorkspaceObject_Impl.hpp
Labels: component - Model, Pull Request - Ready for CI

#5135 Add native support for measure argument methods in OsLib_HelperMethods, try 2
  src/measure/OSArgument.cpp
  src/measure/OSArgument.hpp
  src/measure/OSRunner.cpp
  src/measure/OSRunner.hpp
  src/measure/test/MeasureFixture.cpp
  src/measure/test/MeasureFixture.hpp
  src/measure/test/OSArgument_GTest.cpp
  src/measure/test/OSRunner_GTest.cpp
  src/utilities/core/CommonImport.i
  src/utilities/core/Enum.i
  src/utilities/data/Attribute.cpp
  src/utilities/data/Attribute.hpp
  src/utilities/data/Attribute_Impl.hpp
  src/utilities/data/Test/Attribute_GTest.cpp
  src/utilities/data/Test/Variant_GTest.cpp
  src/utilities/data/Variant.cpp
  src/utilities/data/Variant.hpp
  src/utilities/filetypes/WorkflowStepResult.cpp
  src/utilities/filetypes/WorkflowStepResult.hpp
  src/utilities/filetypes/WorkflowStepResult_Impl.hpp
  src/utilities/geometry/Geometry.i
  src/workflow/ApplyMeasure.cpp
Labels: Pull Request - Ready for CI

#5146 Fix typo in ReportingMeasure template measure.py + use pathlib.Path in tests
  src/utilities/bcl/templates/EnergyPlusMeasure/tests/test_energyplus_measure.py
  src/utilities/bcl/templates/ModelMeasure/tests/test_model_measure.py
  src/utilities/bcl/templates/ReportingMeasure/measure.py
  src/utilities/bcl/templates/ReportingMeasure/tests/test_reporting_measure.py
Labels: python

#5148 Improve the conan to build flow.
  BUILDING.md
  conanfile.py
Labels: Developer Issue, Pull Request - Ready for CI, component - Conan

#5158 Find system ruby 3.2
  CMake/FindRuby.cmake
  ruby/test/CMakeLists.txt
Labels: Developer Issue

#5154 Preserve SubSurface Outside Boundary Condition Object in ModelMerger
  src/model/ModelMerger.cpp
  src/model/test/ModelMerger_GTest.cpp
Labels: component - Geometry Editor, Pull Request - Ready for CI

#5149 Fix #5147 and generally modernize measure templates + get openstudio to run pytest
  CMake/FindRuby.cmake
  CMakeLists.txt
  python/requirements.txt
  ruby/engine/embedded_help.rb
  ruby/engine/test/RubyEngine_GTest.cpp
  ruby/test/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/cli/MeasureUpdateCommand.cpp
  src/cli/test/test_bcl_measure_templates.py
  src/utilities/bcl/BCLMeasure.cpp
  src/utilities/bcl/templates/EnergyPlusMeasure/tests/energyplus_measure_test.rb
  src/utilities/bcl/templates/EnergyPlusMeasure/tests/test_energyplus_measure.py
  src/utilities/bcl/templates/ModelMeasure/tests/example_model.osm
  src/utilities/bcl/templates/ModelMeasure/tests/model_measure_test.rb
  src/utilities/bcl/templates/ModelMeasure/tests/test_model_measure.py
  src/utilities/bcl/templates/ReportingMeasure/tests/example_model.osm
  src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb
  src/utilities/bcl/templates/ReportingMeasure/tests/test_reporting_measure.py
Labels: component - Measures, Pull Request - Ready for CI, component - Ruby bindings, component - Python bindings

#5159 Debug bundler
  CMakeLists.txt
  ruby/bindings/InitRubyBindings.cpp
  ruby/test/ApplicationPathHelpers_Test.rb
  ruby/test/Attribute_Test.rb
  ruby/test/Calendar_Test.rb
  ruby/test/Checksum_Test.rb
  ruby/test/ClimateZones_Test.rb
  ruby/test/Comments_Test.rb
  ruby/test/Component_Test.rb
  ruby/test/Construction_Test.rb
  ruby/test/DateTime_Test.rb
  ruby/test/Date_Test.rb
  ruby/test/ElectricLoadCenterDistribution_Test.rb
  ruby/test/Enum_Test.rb
  ruby/test/EpwFile_Test.rb
  ruby/test/ExceptionHandling1_Test.rb
  ruby/test/ExceptionHandling3_Test.rb
  ruby/test/ExteriorLights_Test.rb
  ruby/test/Facility_Test.rb
  ruby/test/Gltf_Test.rb
  ruby/test/IddEnums_Test.rb
  ruby/test/IddObject_Test.rb
  ruby/test/InteriorPartitionSurface_Test.rb
  ruby/test/Logger_Test.rb
  ruby/test/Matrix_Test.rb
  ruby/test/Optional_Test.rb
  ruby/test/Path_Test.rb
  ruby/test/QuantityRegex_Test.rb
  ruby/test/Quantity_Test.rb
  ruby/test/RubyOperations_Test.rb
  ruby/test/ScaleFactory_Test.rb
  ruby/test/ScheduleConstant_Test.rb
  ruby/test/SimulationControl_Test.rb
  ruby/test/Site_Test.rb
  ruby/test/SkyTemperature_Test.rb
  ruby/test/Space_Test.rb
  ruby/test/Surface_Test.rb
  ruby/test/TimeSeries_Test.rb
  ruby/test/Time_Test.rb
  ruby/test/Transformation_Test.rb
  ruby/test/UUID_Test.rb
  ruby/test/Unit_Test.rb
  ruby/test/Vector_Test.rb
  ruby/test/WorkspaceObjectWatcher_Test.rb
  ruby/test/Workspace_Test.rb
  ruby/test/epJSON_Test.rb
  src/cli/UpdateCommand.cpp
  src/cli/test/bundle/Gemfile
  src/cli/test/bundle/test.rb
  src/cli/test/test_with_analysis.py
Labels: Developer Issue, Pull Request - Ready for CI

#5171 logger test: missing `require 'logger'`.
  src/cli/test/logger_test.rb
Labels: Developer Issue, Pull Request - Ready for CI

#5170 Fix #5133 - Conversion to/from pathlib.Path in python bindings now rejects openstudio.Path
  python/test/test_usability.py
  src/utilities/core/Path.i
Labels: severity - Normal Bug, Pull Request - Ready for CI, component - Python bindings

#5168 Fix #5167 - measure.xml default bool values reported as 0/1 on develop
  src/measure/OSArgument.cpp
Labels: component - Measures, Developer Issue, Pull Request - Ready for CI

#5165 IRB Debug Init + byebug
  CMakeLists.txt
  ruby/bindings/InitRubyBindings.cpp
  ruby/engine/embedded_help.rb
  src/cli/test/run_with_byebug.rb
Labels: Enhancement Request, component - CLI, Pull Request - Ready for CI, component - Ruby bindings
