Repository NREL/OpenStudio, pull requests merged in 2025-03, with the labels that each got.

#5361 Fix typo in StandardsInformationConstruction
  src/model/StandardsInformationConstruction.cpp
Labels: Pull Request - Ready for CI

#5354 Update to v25.1.0-IOFreeze
  CMakeLists.txt
  resources/energyplus/ProposedEnergy+.idd
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateSpaceInfiltrationDesignFlowRate.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateZoneVentilationDesignFlowRate.cpp
  src/energyplus/Test/CoilWaterHeatingDesuperheater_GTest.cpp
  src/energyplus/Test/ZoneVentilationDesignFlowRate_GTest.cpp
  src/model/AirflowNetworkEquivalentDuct.cpp
  src/model/SpaceInfiltrationDesignFlowRate.cpp
  src/model/SpaceInfiltrationDesignFlowRate.hpp
  src/model/SpaceInfiltrationDesignFlowRate_Impl.hpp
  src/model/ThermalZone.cpp
  src/model/ZoneVentilationDesignFlowRate.cpp
  src/model/ZoneVentilationDesignFlowRate.hpp
  src/model/ZoneVentilationDesignFlowRate_Impl.hpp
  src/model/ZoneVentilationWindandStackOpenArea.cpp
  src/model/test/SpaceInfiltrationDesignFlowRate_GTest.cpp
  src/model/test/ZoneVentilationDesignFlowRate_GTest.cpp
  src/osversion/VersionTranslator.cpp
  src/osversion/VersionTranslator.hpp
  src/osversion/test/3_10_0/test_vt_GroundHeatExchangerVertical.osm
  src/osversion/test/3_10_0/test_vt_GroundHeatExchangerVertical.rb
  src/osversion/test/3_10_0/test_vt_SpaceInfiltrationDesignFlowRate.osm
  src/osversion/test/3_10_0/test_vt_SpaceInfiltrationDesignFlowRate.rb
  src/osversion/test/3_10_0/test_vt_WaterHeaterHeatPump.osm
  src/osversion/test/3_10_0/test_vt_WaterHeaterHeatPump.rb
  src/osversion/test/3_10_0/test_vt_ZoneVentilationDesignFlowRate.osm
  src/osversion/test/3_10_0/test_vt_ZoneVentilationDesignFlowRate.rb
  src/osversion/test/VersionTranslator_GTest.cpp
  src/utilities/idd/Test/IddFile_GTest.cpp
Labels: Pull Request - Ready for CI, IDDChange

#5365 Fix #5355 - E+ 25.1.0: Wrap OutputControl:ResilienceSummaries
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateOutputControlResilienceSummaries.cpp
  src/energyplus/ReverseTranslator.cpp
  src/energyplus/ReverseTranslator.hpp
  src/energyplus/ReverseTranslator/ReverseTranslateOutputControlResilienceSummaries.cpp
  src/energyplus/Test/OutputControlResilienceSummaries_GTest.cpp
  src/model/CMakeLists.txt
  src/model/ConcreteModelObjects.hpp
  src/model/Model.cpp
  src/model/Model.hpp
  src/model/ModelSimulation.i
  src/model/Model_Impl.hpp
  src/model/OutputControlResilienceSummaries.cpp
  src/model/OutputControlResilienceSummaries.hpp
  src/model/OutputControlResilienceSummaries_Impl.hpp
  src/model/test/Model_GTest.cpp
  src/model/test/OutputControlResilienceSummaries_GTest.cpp
  src/model/test/UniqueModelObject_GTest.cpp
  src/sdd/ForwardTranslator.cpp
Labels: component - Model, Pull Request - Ready for CI, IDDChange

#5366 Update the libgettext hash for building the Openstudio in NREL network.
  conan.lock
Labels: Pull Request - Ready for CI

#5349 fixed all the unittests from #5327
  src/utilities/bcl/BCL.hpp
Labels: severity - Minor Bug, Pull Request - Ready for CI

#5369 #5368 - Wrap OutputTableAnnual and OutputTableMonthly
  developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_10_0_TDB.md
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateOutputTableAnnual.cpp
  src/energyplus/ForwardTranslator/ForwardTranslateOutputTableMonthly.cpp
  src/energyplus/ReverseTranslator.cpp
  src/energyplus/ReverseTranslator.hpp
  src/energyplus/ReverseTranslator/ReverseTranslateOutputTableAnnual.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateOutputTableMonthly.cpp
  src/energyplus/Test/OutputTableAnnual_GTest.cpp
  src/energyplus/Test/OutputTableMonthly_GTest.cpp
  src/model/CMakeLists.txt
  src/model/ConcreteModelObjects.hpp
  src/model/Model.cpp
  src/model/ModelCore.i
  src/model/OutputTableAnnual.cpp
  src/model/OutputTableAnnual.hpp
  src/model/OutputTableAnnual_Impl.hpp
  src/model/OutputTableMonthly.cpp
  src/model/OutputTableMonthly.hpp
  src/model/OutputTableMonthly_Impl.hpp
  src/model/ScheduleTypeRegistry.cpp
  src/model/test/OutputTableAnnual_GTest.cpp
  src/model/test/OutputTableMonthly_GTest.cpp
Labels: component - Measures, Enhancement Request, component - Model, component - IDF Translation, Pull Request - Ready for CI, IDDChange

#5358 Remove allowedObjects check from `energyPlusOutputRequests`
  src/workflow/Util.cpp
  src/workflow/Util.hpp
  src/workflow/test/Util_GTest.cpp
Labels: component - Measures, Pull Request - Ready for CI

#5376 Add workflow_dispatch to C#/python bindings workflows, so we can at least periodically test them
  .github/workflows/buildCSharp.yml
  .github/workflows/python_bindings.yml
Labels: Developer Issue

#5374 Fix #5307 - DefrostEnergyInputRatioModifierFunctionofTemperatureCurve is orphaned when AirConditionerVariableRefrigerantFlow is removed
  src/model/AirConditionerVariableRefrigerantFlow.cpp
  src/model/test/AirConditionerVariableRefrigerantFlow_GTest.cpp
Labels: severity - Minor Bug, component - Model, Pull Request - Ready for CI

#5382 Add a helper `IdfObject::initializeFields(bool fill_default)` + Fix CMake warnings and speed up build of openstudio_utilities_tests
  CMakeLists.txt
  ProjectMacros.cmake
  src/lib/CMakeLists.txt
  src/lib/test/ApplicationPathHelpers_GTest.cpp
  src/utilities/CMakeLists.txt
  src/utilities/core/test/ApplicationPathHelpers_GTest.cpp
  src/utilities/idd/Idd.i
  src/utilities/idd/IddField.cpp
  src/utilities/idd/IddField.hpp
  src/utilities/idf/IdfObject.cpp
  src/utilities/idf/IdfObject.hpp
  src/utilities/idf/IdfObject_Impl.hpp
  src/utilities/idf/Test/IdfObject_GTest.cpp
Labels: Developer Issue, Pull Request - Ready for CI

#5379 Update to E+ v25.1.0-RC1
  CMakeLists.txt
  src/model/CoilCoolingWater.cpp
  src/model/CoilHeatingWater.cpp
Labels: Pull Request - Ready for CI

#5373 Fix #5309 - ThreeJSForwardTranslator adds unnecessary RenderingColor objects for AirLoopHVAC
  src/model/ThreeJSForwardTranslator.cpp
  src/model/test/ThreeJSForwardTranslator_GTest.cpp
Labels: severity - Minor Bug, Pull Request - Ready for CI, component - Geometry Translator

#5378 Fix #4994 - Old materials OSC (< 0.7.4) cannot be loaded anymore
  src/osversion/VersionTranslator.cpp
  src/osversion/test/0_7_0/Brick_Fired_Clay_4_in_130_lb_ft3.osc
  src/osversion/test/VersionTranslator_GTest.cpp
Labels: severity - Normal Bug, component - Version Translator, Pull Request - Ready for CI

#5372 Fix #5371 - add FuelTypes to PlantComponentUserDefined
  src/model/EnergyManagementSystemMeteredOutputVariable.cpp
  src/model/EnergyManagementSystemMeteredOutputVariable.hpp
  src/model/EnergyManagementSystemMeteredOutputVariable_Impl.hpp
  src/model/EnergyManagementSystemProgram.cpp
  src/model/EnergyManagementSystemProgram.hpp
  src/model/EnergyManagementSystemProgram_Impl.hpp
  src/model/EnergyManagementSystemSubroutine.cpp
  src/model/EnergyManagementSystemSubroutine.hpp
  src/model/EnergyManagementSystemSubroutine_Impl.hpp
  src/model/PlantComponentUserDefined.cpp
  src/model/PlantComponentUserDefined.hpp
  src/model/PlantComponentUserDefined_Impl.hpp
  src/model/test/EnergyManagementSystemMeteredOutputVariable_GTest.cpp
  src/model/test/EnergyManagementSystemProgram_GTest.cpp
  src/model/test/EnergyManagementSystemSubroutine_GTest.cpp
  src/model/test/PlantComponentUserDefined_GTest.cpp
  src/utilities/data/DataEnums.hpp
Labels: component - Standards, component - Model, Pull Request - Ready for CI
