Repository NREL/OpenStudio, pull requests merged in 2025-06, with the labels that each got.

#5419 Get E+ mac tar.gz from E+ release (hot swapped the binaries)
  CMakeLists.txt
Labels: Developer Issue, Pull Request - Ready for CI

#5426 #1697 - Re-wrap Thermochromic window model properly to handle extensible fields and translation to/from EnergyPlus
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateThermochromicGlazing.cpp
  src/energyplus/ReverseTranslator.cpp
  src/energyplus/ReverseTranslator.hpp
  src/energyplus/ReverseTranslator/ReverseTranslateMaterialPropertyGlazingSpectralData.cpp
  src/energyplus/ReverseTranslator/ReverseTranslateWindowMaterialGlazingGroupThermochromic.cpp
  src/energyplus/Test/ThermochromicGlazing_GTest.cpp
  src/model/CMakeLists.txt
  src/model/ModelResources.i
  src/model/ThermochromicGlazing.cpp
  src/model/ThermochromicGlazing.hpp
  src/model/ThermochromicGlazing_Impl.hpp
  src/model/test/ThermochromicGlazing_GTest.cpp
Labels: severity - Normal Bug, component - Model, component - IDF Translation, Pull Request - Ready for CI

#5427 Fix: Update OpenStudio gems to RC2
  CMakeLists.txt
Labels: Pull Request - Ready for CI

#5430 updating gems to include standards offical 0.8.0 release
  CMakeLists.txt
Labels: Pull Request - Ready for CI

#5433 updates gems for standards 0.8.1 and update to rc5
  CMakeLists.txt
Labels: Pull Request - Ready for CI

#5437 Bump openstudio-gems to v3.10.0-2 which uses openstudio-standards 0.8.2
  CMakeLists.txt
Labels: component - CLI, component - Standards, component - Ruby bindings

#5440 Add an AlmaLinux9 (centos9) E+ package
  CMakeLists.txt
  ruby/test/CMakeLists.txt
Labels: Developer Issue

#5445 testing out linux incremental build
  .github/workflows/incremental-build.yml
  .github/workflows/mac.yml
  .github/workflows/windows.yml
  .gitignore
  Jenkinsfile_develop_ubuntu_2204
Labels: Pull Request - Ready for CI
