Repository NREL/OpenStudio, pull requests merged in 2025-01, with the labels that each got.

#5337 Fixes `UnitarySystemPerformance:Multispeed` number of cooling speeds w/ `Coil:Cooling:DX`
  src/energyplus/ForwardTranslator/ForwardTranslateUnitarySystemPerformanceMultispeed.cpp
Labels: component - HVAC, Pull Request - Ready for CI

#5341 Fix floorplanjs issue
  src/utilities/geometry/FloorplanJS.cpp
Labels: severity - Normal Bug, Pull Request - Ready for CI

#5322 Fix #5313 - AirLoopHVACUnitaryHeatPump(Multispeed) fixes
  resources/model/OpenStudio.idd
  src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp
  src/model/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed.cpp
  src/model/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_Impl.hpp
  src/model/AirLoopHVACUnitaryHeatPumpAirToAir_Impl.hpp
  src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp
  src/model/test/AirLoopHVACUnitaryHeatPumpAirToAir_GTest.cpp
Labels: severity - Normal Bug, component - HVAC, component - Model, Pull Request - Ready for CI

#5346 Fix #5339 - Fixup Idd units m3/s -> gal/min
  resources/model/OpenStudio.idd
Labels: Enhancement Request, Pull Request - Ready for CI, IDDChange

#5345 Fix #5343 - Design Range Temperature for OS:CoolingTower:SingleSpeed is not being converted into EnergyPlus
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator/ForwardTranslateCoolingTowerSingleSpeed.cpp
  src/energyplus/Test/CoolingTowerSingleSpeed_GTest.cpp
Labels: severity - Normal Bug, component - IDF Translation, Pull Request - Ready for CI

#5326 Wrap ZoneHVAC:EvaporativeCoolerUnit
  developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_9_1_TDB.md
  resources/model/OpenStudio.idd
  src/energyplus/CMakeLists.txt
  src/energyplus/ForwardTranslator.cpp
  src/energyplus/ForwardTranslator.hpp
  src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACEvaporativeCoolerUnit.cpp
  src/energyplus/Test/ZoneHVACEvaporativeCoolerUnit_GTest.cpp
  src/model/CMakeLists.txt
  src/model/ConcreteModelObjects.hpp
  src/model/EvaporativeCoolerDirectResearchSpecial.cpp
  src/model/EvaporativeCoolerDirectResearchSpecial_Impl.hpp
  src/model/EvaporativeCoolerIndirectResearchSpecial.cpp
  src/model/EvaporativeCoolerIndirectResearchSpecial_Impl.hpp
  src/model/FanComponentModel.cpp
  src/model/FanConstantVolume.cpp
  src/model/FanOnOff.cpp
  src/model/FanSystemModel.cpp
  src/model/FanVariableVolume.cpp
  src/model/Model.cpp
  src/model/ModelZoneHVAC.i
  src/model/ScheduleTypeRegistry.cpp
  src/model/ZoneHVACEvaporativeCoolerUnit.cpp
  src/model/ZoneHVACEvaporativeCoolerUnit.hpp
  src/model/ZoneHVACEvaporativeCoolerUnit_Impl.hpp
  src/model/test/ZoneHVACEvaporativeCoolerUnit_GTest.cpp
Labels: Enhancement Request, component - HVAC, Pull Request - Ready for CI, IDDChange
